### ISSUE TITLE
How to set SSML parsing to on at user configuration file?

### ISSUE THREAD

**Issue by guest271314** [brailcom/speechd#1]
Presently Chromium browser does not provide a means to set `x` option to parse SSML when calling `window.speechSynthesis.speak()`, see [Implement SSML parsing at SpeechSynthesisUtterance](https://bugs.chromium.org/p/chromium/issues/detail?id=795371) when [`--enable-speech-dispatcher`](https://peter.sh/experiments/chromium-command-line-switches/#enable-speech-dispatcher) flag is set. 

Have created a user configuration file using `spd-conf -u` though have not located documentation or code relevant to setting SSML parsing on by default for `spd-say` or `espeak` `m` option when `espeak` is set as default module.

How to set SSML parsing to on for all unix socket connections from Chromium browser?

**Comment by alexarnaud** [comment]
Hello @guest271314,

Here is not a support channel but a bug report platform.

To ask question you could use the speech-dispatcher mailing list : https://lists.freebsoft.org/mailman/listinfo/speechd

Best regards.

**Comment by guest271314** [comment]
@alexarnaud  https://lists.freebsoft.org/pipermail/speechd/2017q4/004982.html

**Comment by guest271314** [comment]
@alexarnaud The email to the mailing list is still unanswered. Who needs to be contacted to get an answer to the question as to how to set `SSML_MODE` to `on` for all calls to the binary, or at least all unix socket connection?

**Comment by guest271314** [comment]
@alexarnaud  According to this message speech-dispatcher is migrating to GitHub unless not interpreting the message correctly

> Hi,
> 
> 
> I am very happy to see speech-dispatcher maintained after this sad news
> of Luke's departure. Hypra will try helping as much as possible too.
> Just we recommend to inform the wide community when the migration to
> Github is effective, so that there is a large communicatin about it, as
> it is the best way to increase contributions for maintainance and improving.
> 
> 
> Best regards,
> 
> 
> signature_jp_2
> Logo Hypra 	JEAN-PHILIPPE MENGUAL
> 

Does that not make this repository the venue to improve speech-dispatcher? 

The ability to turn on SSML parsing at the user configuration file parsing would be an improvement from perspective here.

https://lists.freebsoft.org/pipermail/speechd/2017q4/004981.html

**Comment by alexarnaud** [comment]
Le 29/01/2018 à 03:58, guest271314 a écrit :
> @alexarnaud <https://github.com/alexarnaud> The email to the mailing 
> list is still unanswered. Who needs to be contacted to get an answer to 
> the question as to how to set |SSML_MODE| to |on| for all calls to the 
> binary, or at least all unix socket connection?
I don't know  which one could answer your question. I can read your 
message but I can't understand it because I found it too difficult to 
read. For sure, I don't have the skills to give you the answer you 
requested.

To be honest, It's my principal issue when I'm writing mail. I think a 
message should be really didactic and simple to make people want read 
it, understand it and answer it. People will take time for you and don't 
want to spend time to understand a message.

Best regards.
-- 
Alex ARNAUD

**Comment by guest271314** [comment]
@alexarnaud Simply put: 

1. How to enable SSML parsing at user configuration file?
2. How to enable SSML parsing at speech-dispatcher system wide configuration file?

Purpose:

1. For all calls to `spd-say` or `espeak`, or whatever speech synthesis engine that is used which has SSML capabilities to parse SSML input either by by inet connection or unix socket connection

Could locate no such capabilities at the documentation. 

According to 

> Speech Dispatcher moves to GitHub under a new maintainer
>
> Dear all,
> 
> we are pleased to let you know that the Speech Dispatcher project which is a common high-level interface to speech synthesis was now moved to a new repository on GitHub. This brings easier code review capabilities, smoother contribution process and convenient issue tracking on a platform that is already very well known to many. We hope this will make it easier for others to contribute to its development and we invite everyone interested to cooperate.
> 
> The new repository is:
>         https://github.com/brailcom/speechd
> 
> Bugs can be reported and suggestions can be provided at:
>         https://github.com/brailcom/speechd/issues
> 
> Also speechd-el, the Emacs speech and Braille output interface, as well as a few other projects related to Speech Dispatcher were moved to GitHub:
>         https://github.com/brailcom/
> 
> As some of you already know, the Speech Dispatcher project has also recently changed its maintainer. The new leader of the project is now Samuel Thibault. We would like to use this opportunity to repeat our many thanks to Luke Yelavich who worked in this important role previously and to wish to Samuel and the Speech Dispatcher project all the best for the future.
> 
> Hynek Hanke & the team from BRAILCOM,o.p.s.
> Samuel Thibault & Hypra

this is the venue to ask such questions.

**Comment by sthibaul** [comment]
Well, stricly speaking, this is an issue tracker, not a help channel :)
The truth is: way more people are reading the mailing list than the people who are watching the issue tracker, so you had way better chance of getting an answer on the list than here. If the list didn't answer, then nobody knows, and somebody has to dive into the source code to determine the answer.

**Comment by sthibaul** [comment]
Concerning the actual issue, I don't think being able to set ssml by default in the user configuration is a desirable feature, because it'll have a lot of unanticipated consequences. Normally it's the tool that submits data to speechd which declares whether that is pure text or ssml.

For instance, spd-say does have a -x option to enable ssml. If an application uses the API, it should use spd_set_data_mode() to enable ssml.

**Comment by sthibaul** [comment]
About the chromium case, I guess window.speechSynthesis.speak() is a chromium-provided API? Then they have to add a flag that allows to specify that the content is SSML. Going around that would pose way more problems on the long run than it solves on the short term.

**Comment by sthibaul** [comment]
Looking at the actual trackers on chromium, I can confirm that the bug is really there. Something like the attached patch would be just enough to fix it there for everybody, instead of working around it only for the few people who happen to know about it.

[ssml.txt](https://github.com/brailcom/speechd/files/1677168/ssml.txt)
