### ISSUE TITLE
How to install using git repository?

### ISSUE THREAD

**Issue by guest271314** [brailcom/speechd#10]
Getting errors following instructions at [INSTALL ](https://github.com/brailcom/speechd/blob/master/INSTALL)

```
./configure: line 12297: syntax error near unexpected token `0.40.0'
./configure: line 12297: `IT_PROG_INTLTOOL(0.40.0)'
~/speechd-master$ make all
make: *** No rule to make target 'all'.  Stop.
```

**Comment by alexarnaud** [comment]
Le 18/02/2018 à 21:37, guest271314 a écrit :
> Getting errors following instructions at INSTALL 
> <https://github.com/brailcom/speechd/blob/master/INSTALL>
> 
> |./configure: line 12297: syntax error near unexpected token `0.40.0' 
> ./configure: line 12297: `IT_PROG_INTLTOOL(0.40.0)' ~/speechd-master$ 
> make all make: *** No rule to make target 'all'. Stop. |
> 

What is your build environment?

Best regards.

**Comment by guest271314** [comment]
*nix kernel 4.13.0-32-lowlatency

Apparently gettext version is part of the issue

```
~/speechd$ autoreconf -i
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.19.8 but this version
               is older. Please upgrade to gettext-0.19.8 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

**Comment by sthibaul** [comment]
Do you have libtool installed, as documented?

**Comment by sthibaul** [comment]
Ah, no, it seems it's intltool/gettext which is needed

**Comment by guest271314** [comment]
@sthibaul Yes. There is some issue with `gettext` version. Downloaded version 0.19.8 from https://ftp.gnu.org/gnu/gettext/. Installing now. Will try again and post result here.

**Comment by guest271314** [comment]
@sthibaul Why has the issue been closed without verification of being resolved? What are the exact steps necessary to install `speech-dispatcher` from this github repository?

**Comment by sthibaul** [comment]
Well, everything in the bug report points at the missing intltool/gettext package, so closing the bugs means I really think that's the issue. If it's not, then feel free to reopen it.
