### ISSUE TITLE
With Speech Dispatcher 0.9RC2, it is not possible to list voices in certain circonstances

### ISSUE THREAD

**Issue by alexarnaud** [brailcom/speechd#173]
Hello all,

Environment:
- Debian Stretch or Debian Buster
- Orca 3.30.1 from backports or Orca from Debian experimental
- Speech Dispatcher 0.9RC2 or Speech Dispatcher from Debian experimantal

Steps to reproduce:
1) Launch Orca with this command
killall speech-dispatcher; speech-dispatcher; orca --replace
2) Go to voice tab
3) Check the available list 

Result: 
List or voices is empty

Expected result:
List of voices should be available

This issue seems random on the computer of one my colleague, on my computer, it's always present.

Best regards,
Alex.

**Comment by sthibaul** [comment]
Which speech synthesizer is used?

Perhaps check with `spd-say -O` and `spd-say -o thesynthesizer -L` whether it's working.

Also, the speech-dispatcher logs would be helpful, as seen in `/run/user/.../speech-dispatcher, both the speech dispatcher log and the synthesizer log.

**Comment by cwendling** [comment]
I can confirm that with master I don't get any voices listed in Orca, yet I get them on the CLI with `spd-say -L`.
speechd logs seems to properly send voices, I can see the list getting sent (many lines finishing with `LINE here:|200 OK VOICE LIST SENT|`) when orca's setup window appears.

Does the list format changed in a way affecting Orca's retrieval?

**Comment by sthibaul** [comment]
It seems that Luke changed it to tabs instead of spaces, yes

**Comment by sthibaul** [comment]
(but that should be handled by the speechd library)

**Comment by sthibaul** [comment]
Ah, no, spd_list_voices returns them as is, with the tabs.

**Comment by cwendling** [comment]
OK, so I withdraw my remark: it works fine for me if I get Orca to use the updated python3-speechd.

@alexarnaud try running your orca with `PYTHONPATH=/usr/local/lib/python3.6/site-packages:/usr/local/lib/python3.6/dist-packages orca --replace`

**Comment by cwendling** [comment]
@sthibaul OK so we confirm that it works fine, but it means that the Debian packages should make sure one can't keep a too old python3-speechd (e.g. getting pseech-dispatcher to conflict with python3-speechd < 0.9 or so, or even making it require the same version)

**Comment by alexarnaud** [comment]
@cwendling Jean-Philippe and me confirms the fix, thanks @cwendling 

We're proposing to add a conflict into the Debian package in consequence. We'll report a bug in the Debian side for that.

Also we should check how a tester can uses speech-dispatcher master without having to configure it's computer in a complicated way.

Best regards,
Alex.

**Comment by sthibaul** [comment]
Ok, I'll add that. Thanks!

**Comment by cwendling** [comment]
@sthibaul I created a report on Debian's side: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914365
