### ISSUE TITLE
Disturbs audio during startup

### ISSUE THREAD

**Issue by sthibaul** [brailcom/speechd#198]
It has been reported (though apparently never directly to speechd...) that when speech-dispatcher starts, the system audio gets disturbed. That can be heard by starting speech-dispatcher while some sound is playing.

**Comment by alexarnaud** [comment]
You could find related bugs here: 
https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1736222 
and https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1739310
and a reddit thread: 
https://www.reddit.com/r/firefox/comments/7n5vn6/linux_firefox_and_speechdispatcher_are_making/

Best regards,
Alex.

Le 21/12/2018 à 10:28, Samuel Thibault a écrit :

**Comment by sthibaul** [comment]
FI, I get the same kind of effect when I start qemu (with pulseaudio backend) while playing audio in firefox.

**Comment by dobey** [comment]
This is I think not related to speechd, but is a problem with pulseaudio. At some point in the past couple of years (without ever having used speechd at the time), I had noticed that pulseaudio would start distorting audio after starting a VM in qemu, or when starting a game under Steam. I also discovered that if I keep either `pavucontrol` or GNOME's sound setting panel open during my login session, this problem would no longer happen.

**Comment by alexarnaud** [comment]
On my own tests, this issue seems worse since I've moved from Debian 9 to 10. It takes at least 30 seconds between the startup with sound crackling and to have a clear sound. Sometimes I need to restart Speech Dispatcher 2 or 3 times or restart PulseAudio to have a correct sound.

**Comment by dobey** [comment]
To further expand on my previous comment, I'll note that I only had this problem when using a USB audio interface. After switching to on-board audio and no longer using the USB interface for audio, I now have never once encountered this issue again, nor with qemu or other software. Nor do I get the loud bumps from the amplifier powering on/off when rebooting any longer. This seems to be an issue with pulseaudio and power management with USB audio devices.

**Comment by sthibaul** [comment]
Just to give an update on this: I got a look at the pulseaudio logs, and saw this:

- while having such disturbance, the log shows repeatedly
```
D: [alsa-sink-ALC3271 Analog] protocol-native.c: Implicit underrun of 'playback'
D: [alsa-sink-ALC3271 Analog] sink.c: alsa_output.pci-0000_00_1f.3.analog-stereo: Found underrun 28 bytes ago (68 bytes ahead in playback buffer)
D: [alsa-sink-ALC3271 Analog] sink.c: alsa_output.pci-0000_00_1f.3.analog-stereo: Found underrun 60 bytes ago (36 bytes ahead in playback buffer)
D: [alsa-sink-ALC3271 Analog] sink.c: alsa_output.pci-0000_00_1f.3.analog-stereo: Found underrun 92 bytes ago (4 bytes ahead in playback buffer)
D: [alsa-sink-ALC3271 Analog] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-ALC3271 Analog] alsa-sink.c: Requested to rewind 96 bytes.
D: [alsa-sink-ALC3271 Analog] alsa-sink.c: Mhmm, actually there is nothing to rewind.
```
the "actually there is nothing to rewind" frightens me a bit :) and could explain why sometimes we hear ghosts that repeat previous audio.
- at some point, one gets
```
I: [alsa-sink-ALC3271 Analog] alsa-sink.c: Scheduling delay of 0,32 ms > 0,25 ms, you might want to investigate this to improve latency...
I: [alsa-sink-ALC3271 Analog] ratelimit.c: 303 events suppressed
I: [alsa-sink-ALC3271 Analog] alsa-sink.c: Underrun!
I: [alsa-sink-ALC3271 Analog] alsa-sink.c: Increasing minimal latency to 1,00 ms
D: [alsa-sink-ALC3271 Analog] alsa-sink.c: Latency set to 1,00ms
```
and shortly after
```
I: [alsa-sink-ALC3271 Analog] alsa-sink.c: Underrun!
I: [alsa-sink-ALC3271 Analog] alsa-sink.c: Increasing minimal latency to 2,00 ms
D: [alsa-sink-ALC3271 Analog] alsa-sink.c: Latency set to 2,00ms
```
and from then on I'm not getting any disturbance issue.

So to me this really looks like an issue inside pulseaudio itself, possibly simply triggered by the way speech-dispatcher pushes its output.

**Comment by sthibaul** [comment]
With the attached patch applied to pulseaudio I'm not able to trigger the issue any more

[patch.txt](https://github.com/brailcom/speechd/files/4535728/patch.txt)

**Comment by sthibaul** [comment]
@alexarnaud  @dobey  : Could you try to uncomment 

```
AudioPulseMinLength 1764
```

in your `speechd.conf` file? 1764 is supposed to be the default, but it actually was somehow set to 100 by default, which is hitting the pulseaudio issue, which I have reported on

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/871
