### ISSUE TITLE
Baratinoo: selecting a specific voice and then the default voice doesn't come back to default

### ISSUE THREAD

**Issue by alexarnaud** [brailcom/speechd#203]
Hello all,

Tested environment:
- Debian 9 with speech-dispatcher master and Orca master
- Debian 8 with speech-dispatcher 0.8 with Hypra's patches and Orca 3.24

Steps to reproduce:
1) On Orca, select baratinoo as speech synthesizer
2) Click on the apply button to reload the configuration with Baratinoo voice, by default in French it'll load Philippe
3) Select Agnes and click on apply, it'll load the Agnes voice
4) Switch back to "default voice" and click again on apply

Result:
It stays on Agnes

Expected result:
It should keep the default voice, here Philippe in French

Best regards,
Alex.

**Comment by sthibaul** [comment]
This is actually an issue in Orca itself, to be fixed with https://gitlab.gnome.org/GNOME/orca/-/merge_requests/113
