### ISSUE TITLE
Speaking character should respect capitalization settings applied to speaking strings

### ISSUE THREAD

**Issue by joanmarie** [brailcom/speechd#219]
Type the following in a python3 console:

```
import speechd
client = speechd.SSIPClient("foo")
client.set_cap_let_recogn("none")
client.speak("H")
client.char("H")
```
Expected results: Both `speak()` and `char()` would result in "H" being spoken.

Actual results: `char()` results in "capital H" being spoken, even though the capitalization style is set to none.

If you repeat the above steps, but this time do `client.set_cap_let_recogn("spell")`, both times speech-dispatcher says "capital H". (As I would expect.)

Impact: Orca now relies upon `char()` for speaking a single character. As a result, if an Orca user sets their capitalization style to just use pitch, Orca now says "Capital H" (rather than just "H") in the specified pitch. It is my intent to keep using speech-dispatcher's `char()` to speak single characters because that just seems like the right thing to do. As a result, it would be helpful if speech-dispatcher would apply the capitalization style to `char()`.

Thanks in advance!

**Comment by sthibaul** [comment]
This is unfortunately a synth-specific issue: espeak/espeak-ng do not respect the capital style for character pronunciation. I have reported it to
https://github.com/espeak-ng/espeak-ng/issues/610
