### ISSUE TITLE
provide a proper espeak variant implementation

### ISSUE THREAD

**Issue by sthibaul** [brailcom/speechd#22]
As reported by coffeeking on the freebsoft bug tracker:

“The espeak varient implementation in current speech-dispatcher is functional, but instead of providing a list of varients separate from the usual voices, it simply appends the varients onto the voice list, causing multi thousand long voice lists, causing lots of lag in orca when trying to navigate the lists. If speech-dispatcher were updated to provide a proper speech synth agnostic varient API, leaving the work up to the module maintainers this would correct the problem.”

**Comment by erik-pro** [comment]
doo someone is working on it?

**Comment by sthibaul** [comment]
I'm now working on it.
