### ISSUE TITLE
</speak> pronounced sometimes

### ISSUE THREAD

**Issue by pzajda** [brailcom/speechd#261]
Sometimes SpeechDispatcher pronounces `"</speak>"`.
Using Orca, I encounter this problem on some web pages.

Steps to reproduce with Orca:
1. Open https://www.herboratheque.fr
2. Go to the top of page
3. Jump to the second graphic
4. Go to the next line

After the currency, `"</speak>"` is pronounced, also after the language.

In the case it could be useful, I checked the checkbox to have the same presentation as it is on screen (mode disposition in French) in Orca preferences for FireFox.

**Comment by sthibaul** [comment]
(FTR, to reproduce the reading, enable cursor navigation with F7, press control-home to go to the top, press g two times, then down arrow, to get to the line containing `"Accueil Contact Plan du site € FR"`)

**Comment by sthibaul** [comment]
@pzajda : I can't reproduce the issue. I guess you are using speechd master and orca master? Which speechd voice are you using?

**Comment by sthibaul** [comment]
You could enable Debug in the configuration file of the voice you are using, and post here the corresponding /run/user/*/speech-dispatcher/log/foo.log

**Comment by pzajda** [comment]
Yes, I use Speechd master and Orca master, with Kali, I selected Guillemette.
The log:
[kali.log](https://github.com/brailcom/speechd/files/3477041/kali.log)

**Comment by sthibaul** [comment]
Wed Aug  7 14:34:59 2019 [220044]: Requested data: |<speak>/speak&gt;|

So the issue seems to be coming from Orca. Could you post its log?

**Comment by sthibaul** [comment]
Ah, no, it could be coming from the speechd core. Could you also post the speech-dispatcher.log, with speechd.conf's LogLevel set to 5?

**Comment by sthibaul** [comment]
Mmmm, does it sound the same as the output of

    spd-say -s '<speak></speak>'

?

**Comment by pzajda** [comment]
The Speech-Dispatcher log : 
[speech-dispatcher.log](https://github.com/brailcom/speechd/files/3477200/speech-dispatcher.log)
Do you still need the Orca log?

**Comment by sthibaul** [comment]
I believe I have fixed the issue in speech-dispatcher, but Orca is not supposed to send this bogus output, I'll have a look at the Orca side.

**Comment by sthibaul** [comment]
It seems it's a bug in firefox which returns bogus data.
