### ISSUE TITLE
Add a new parameter to set the Speech-Dispatcher volume to the system one

### ISSUE THREAD

**Issue by alexarnaud** [brailcom/speechd#265]
Hello,

Today I've helped a user who has had his system to a no speech state due to some PulseAudio adjustment made by VLC to increase audio book volume.

To avoid the user to be in a mute Speech Dispatcher state, I propose to create a new configuration parameter called "UseSystemVolume" that will automatically set the Speech Dispatcher volume in PulseAudio to the system level at startup.

Best regards.

**Comment by sthibaul** [comment]
That's going in contradiction with what pulseaudio wants (making the decision external to the application), but this is indeed a critical situation, since the user has no way to bump the volume up.

I'm however wondering if using the system volume is a good idea either, since that one could be muted as well... Maybe a `StartupVolume` option which overrides everything?

**Comment by alexarnaud** [comment]
> I'm however wondering if using the system volume is a good idea either, since that one could be muted as well... Maybe a `StartupVolume` option which overrides everything?

It's a really good idea, yes. An option called "MinimumStartupVolume" that will disable mute and increase the volume only if it is lower than it.

Best regards.

**Comment by sthibaul** [comment]
Apparently this requires using a more involved interface than the mere `pa_simple_*`

**Comment by alexarnaud** [comment]
I found a "work around" to avoid such sound issue, it is disabling flat-volume which makes it impossible for an application to break the whole audio stack. All applications keep the same system volume but one can be at 100%/120% but at the application level, not PulseAudio one.

As PulseAudio has the feature I'd expect to see in Speech Dispatcher, I'm suggesting to close this issue.
