### ISSUE TITLE
dangling symlinks to es_419/emojis.dic for Latin American Spanish languages when using DESTDIR

### ISSUE THREAD

**Issue by denbrice** [brailcom/speechd#271]
Hi,

I've noticed that an installation to a DESTDIR has faulty symlinks pointing to the buildroot instead of the real folder for languages that use emojis from es_419.

The error is in locale/Makefile.am : line 220

$(LN_S) "$(DESTDIR)$(localedatadir)/es_419/emojis.dic" "$(DESTDIR)$(localedatadir)/$$lang419/emojis.dic" || true ;\

should be:
$(LN_S) "$(localedatadir)/es_419/emojis.dic" "$(DESTDIR)$(localedatadir)/$$lang419/emojis.dic" || true ;\

or (even better IMHO):
$(LN_S) "../es_419/emojis.dic" "$(DESTDIR)$(localedatadir)/$$lang419/emojis.dic" || true ;\
[speechd-20191121-es419-1.txt](https://github.com/brailcom/speechd/files/3876802/speechd-20191121-es419-1.txt)

**Comment by sthibaul** [comment]
@pzajda that's for you :)
