### ISSUE TITLE
Changing punctuations level in Orca doesn't change Speech-Dispatcher punctuation level

### ISSUE THREAD

**Issue by Nardol** [brailcom/speechd#284]
When changing the punctuation level in Orca preferences using Kali, the pronounced punctuations remind the same.
Tested with all punctuation levels, from none to all using last master branch.
With speech-dispatcher 0.9.0 (provided by Hypra(, changing punctuation level works.

**Comment by sthibaul** [comment]
Which versions of speech-dispatcher and kali are you using exactly? Things have changed in that regard in speech dispatcher 0.10.0-rc2 and in kali 5.08.

**Comment by Nardol** [comment]
Speech-Dispatcher version: 0.10.0-rc1-5-gf1c0-dirty
For Kali version, @cwendling asked me to do this command:
```objdump -T /usr/lib/libK* | grep -q setNbCarDemoGlobal && echo OK```
Which displayed "OK" and nothing else.
Which should indicate Kali is the right version as he answered me.

**Comment by sthibaul** [comment]
Please try -rc2, as mentioned above it contains a fix for recent versions of kali.

**Comment by Nardol** [comment]
Sorry, it displayed that because I didn't re-made a ./configure before compiling.
No I have 0.10.0-rc2 displayed.

**Comment by sthibaul** [comment]
Which exact hypra version works?

**Comment by Nardol** [comment]
Speech-dispatcher-kali 0.9.0-7+hypra1 for Speech-Dispatcher the package version is Hypra2.

**Comment by sthibaul** [comment]
@cwendling : it seems @Nardol 's old version of speech-dispatcher-kali works with his version of Kali. Does he need to upgrade his kali to get it working with recent speech-dispatcher-kali? Could we detect the Kali version? 92fd093b7c3cf260cdc431bca7aac825b5a6b0cc is changing the values passed to `SetModeLectureKali` without checking the version of kali.

**Comment by cwendling** [comment]
> it seems @Nardol 's old version of speech-dispatcher-kali works with his version of Kali. Does he need to upgrade his kali to get it working with recent speech-dispatcher-kali?

I don't think so, I looked it up and we do have the same patches in both versions.  And he got the "recent" Kali version as older ones didn't have the `setNbCarDemoGlobal` symbol.

> Could we detect the Kali version? [92fd093](https://github.com/brailcom/speechd/commit/92fd093b7c3cf260cdc431bca7aac825b5a6b0cc) is changing the values passed to `SetModeLectureKali` without checking the version of kali.

Unfortunately, none that I know of.  It doesn't provide any symbol or directive that can be checked.  *maybe* we could hope there's a symbol we could look up and check if it's present or not, but that sounds really hackish.

**Comment by sthibaul** [comment]
>  maybe we could hope there's a symbol we could look up and check if it's present or not, but that sounds really hackish.

It can look hackish, but in practice it should be reliable enough for our needs :)

**Comment by Nardol** [comment]
Looks like this issue is more extended than I thought. I tested #285 and noticed punctuation level also didn't change what was pronounced using Orca.
Then I tested with eSpeak-NG, using master branch 955a2ed and notice the same issue, the same is pronounced on every punctuation levels.

**Comment by sthibaul** [comment]
Ok, now I see the issue. Could you try to uncomment

    SymbolPreprocessingFile "symbols.dic"

in speechd.conf?

**Comment by sthibaul** [comment]
Could you also try  the current master with and without the

    PunctuationSymbolPreprocFile "symbols.dic"

line?

**Comment by Nardol** [comment]
> Ok, now I see the issue. Could you try to uncomment
> 
> ```
> SymbolPreprocessingFile "symbols.dic"
> ```
> 
> in speechd.conf?

When I read text, it like there were only symbols.
Some letters are read but I have some "@" and others symbols.



> Could you also try the current master with and without the
> 
> ```
> PunctuationSymbolPreprocFile "symbols.dic"
> ```
> 
> line?

When commented, punctuation levels change as expected.
When uncommented, I have the same behavior as in the first test.
If I change the punctuation level in Orca, only symbols which should be pronounced are pronounced but the major part of letters are not pronounced.

**Comment by sthibaul** [comment]
Ok, so it's behaving as I would expect now. But apparently there are some things that you don't expect:

> When I read text, it like there were only symbols.
> Some letters are read but I have some "@" and others symbols.

What do you mean exactly?

> only symbols which should be pronounced are pronounced but the major part of letters are not pronounced.

What do you mean exactly?

Please provide precise examples of what is happening wrongly and how it should actually be happening. Remember that I'm *not* a user of all of this, so I have no idea how the user expects it to behave.

**Comment by Nardol** [comment]
For example, in the browser window where I compose my comment, if I read the title Orca pronounces "c o sd i # 284

When Orca starts:
> l é é
Instead of "lecteur d'écran activé.".

I have set punctuation level to "none".

**Comment by Nardol** [comment]
This issue can be reproduced with spd-say.
Let's have this sentence as an example in French:
"Bonjour à toutes/tos, comment allez-vous ?"

- When punctuation mode is set to none, Speechh-Dispatcher pronounce "b a accent grave"
- When set to "some": "b a barre oblique"
- To all: "b a barre oblique virgule, tiret point d'interrogation"

Tested with eSpeak-NG, with the line activating symbols.dic uncommented.

**Comment by sthibaul** [comment]
I am not getting such kind of behavior. I am running the master branch, and starting:

    spd-say -m all "Bonjour à toutes/tos, comment allez-vous ?"

Whether PunctuationSymbolPreprocFile is commented or not, I am getting the same result, i.e. words are pronounced, and '/', '-', and '?' are spelled.

**Comment by alexarnaud** [comment]
I don't understand why but I'm reproducing the exact same issue if I move the LogLevel from 3 to 5.

**Comment by sthibaul** [comment]
@alexarnaud do you mean that raising the LogLevel changes the behavior, and more precisely triggers the issue?

@Nardol just to  make sure: are you using master? (that includes commit 76e2d672229bdb4d4e36edfd5ea63fccbcb0027f)

**Comment by alexarnaud** [comment]
> @alexarnaud do you mean that raising the LogLevel changes the behavior, and more precisely triggers the issue?

Yes, it's what I mean.

**Comment by Nardol** [comment]
> @Nardol just to make sure: are you using master? (that includes commit [76e2d67](https://github.com/brailcom/speechd/commit/76e2d672229bdb4d4e36edfd5ea63fccbcb0027f))

Yes.
