### ISSUE TITLE
speech-dispatcher.pc.in should refer to *L*GPL-2.1-or-later

### ISSUE THREAD

**Issue by StefanBruens** [brailcom/speechd#287]
https://github.com/brailcom/speechd/blob/76e2d672229bdb4d4e36edfd5ea63fccbcb0027f/speech-dispatcher.pc.in#L3-L6

As the pkgconfig file is about the API library and corresponding headers, it should also say LGPL-2.1-or-later

**Comment by sthibaul** [comment]
@razr : are you Ok with such licence change? since no licence information was specified I had used the default repository licence, but it would indeed make sense to use LGPL instead. I'd just like to make sure you agree

**Comment by razr** [comment]
Samuel, please go forward. It is fine with me

2020-01-23 15:17 GMT-08:00, Samuel Thibault <notifications@github.com>:
> @razr : are you Ok with such licence change? since no licence information
> was specified I had used the default repository licence, but it would indeed
> make sense to use LGPL instead. I'd just like to make sure you agree
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/brailcom/speechd/issues/287#issuecomment-577922393


-- 
Believe is not enough, you must know

**Comment by sthibaul** [comment]
Thanks for the quick reply :)
