### ISSUE TITLE
[Feature Request] Consider Normalizing Text Data Prior to Screen-Reading

### ISSUE THREAD

**Issue by Alexhuszagh** [brailcom/speechd#289]
# Problem

It is increasingly common for users on social media and websites to stylize text with Unicode homoglyphs, often to stylize text. All of these examples are completely illegible to users of a screen-reader, and make actually reading social media content difficult.

For example, with the desired message:
- "Sample text."

We can have users report all of the following outputs, and more:
- "Ｓａｍｐｌｅ　ｔｅｘｔ．"
- "Ⓢⓐⓜⓟⓛⓔ　ⓣⓔⓧⓣ．"
- "𝓢𝓪𝓶𝓹𝓵𝓮 𝓽𝓮𝔁𝓽."
- "𝔖𝔞𝔪𝔭𝔩𝔢 𝔱𝔢𝔵𝔱."
- "𝑺𝒂𝒎𝒑𝒍𝒆 𝒕𝒆𝒙𝒕."
- "𝕊𝕒𝕞𝕡𝕝𝕖 𝕥𝕖𝕩𝕥."

# Potential Solution

A relatively naive, but fairly robust solution is to do Unicode NFKD or NFKC [normalization](https://unicode.org/reports/tr15/) on all inputs. NFKD stands for Normalization Form Compatibility Decomposition, without any recomposition. NFKC stands for Normalization Form Compatibility Decomposition, Followed by Canonical Composition.

In Python, this is fairly trivial:

```python
import unicodedata

def normalize(text):
    return unicodedata.normalize('NFKD', text)
```

For all of the above examples I showed you, it works fairly well:

```python
>>> normalize("𝕊𝕒𝕞𝕡𝕝𝕖 𝕥𝕖𝕩𝕥.")
'Sample text.'
>>> normalize("Ｓａｍｐｌｅ　ｔｅｘｔ．")
'Sample text.'
>>> normalize("Ⓢⓐⓜⓟⓛⓔ　ⓣⓔⓧⓣ．")
'Sample text.'
>>> normalize("𝓢𝓪𝓶𝓹𝓵𝓮 𝓽𝓮𝔁𝓽.")
'Sample text.'
>>> normalize("𝔖𝔞𝔪𝔭𝔩𝔢 𝔱𝔢𝔵𝔱.")
'Sample text.'
>>> normalize("𝑺𝒂𝒎𝒑𝒍𝒆 𝒕𝒆𝒙𝒕.")
'Sample text.'
>>> normalize("𝕊𝕒𝕞𝕡𝕝𝕖 𝕥𝕖𝕩𝕥.")
'Sample text.'
```

# Downsides

There are various situations where this may mildly change the semantics of the input text:

```python
>>> '\ufb01'
'ﬁ'
>>> normalize('\ufb01')
'fi'
```

However, in other cases it should be fine:

```python
>>> 'dæmon'
'dæmon'
>>> normalize('dæmon')
'dæmon'
```

Other issues could occur with the use of confusable homoglyphs:

```python
>>> normalize('𝕀𝕒𝕥𝕖')
Iate
```

Obviously, the desired result would be `late`, however, without a hopelessly complex semantic analysis, this is the best we can do, with minimal boilerplate.

# Current Attempts

There have been previous attempts at fixing this, for example, through the introduction of [font-variants.dic](https://github.com/brailcom/speechd/blob/master/locale/en/font-variants.dic), and has been addressed in #217. However, not only would Unicode NFKC/NFKD normalization solve all these issues, it would also address many homoglyph variants that currently aren't addressed by the above

# Normalization Options

Please note that NFC normalization is considered recommended by W3C (for the web), but screen readers should go one step further. NFC and NFD normalization do not work with the aforementioned styles, and we should have minimal issues with correctness or semantics.

# Other Issues

Some [Unicode blocks](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols) may be commonly used for "stylizing" text but also have significant meaning by mathematicians outside this context. It might be a good idea to ignore characters from certain Unicode blocks, or at the very least provide an option to, since this may hinder the reading of mathematical expressions.

**Comment by Alexhuszagh** [comment]
I just realized most of the codebase is C/C++, so I decided I'd get a working example with libicu just to demonstrate how this shouldn't be a very hard feature to implement, if libicu is a permissible dependency.

```cpp
#include <cassert>
#include <iostream>
#include <string>
#include <unicode/errorcode.h>
#include <unicode/normalizer2.h>

constexpr const char* TESTS[] = {
    u8"Ｓａｍｐｌｅ　ｔｅｘｔ．",
    u8"Ⓢⓐⓜⓟⓛⓔ　ⓣⓔⓧⓣ．",
    u8"𝓢𝓪𝓶𝓹𝓵𝓮 𝓽𝓮𝔁𝓽.",
    u8"𝔖𝔞𝔪𝔭𝔩𝔢 𝔱𝔢𝔵𝔱.",
    u8"𝑺𝒂𝒎𝒑𝒍𝒆 𝒕𝒆𝒙𝒕.",
    u8"𝕊𝕒𝕞𝕡𝕝𝕖 𝕥𝕖𝕩𝕥.",
};

int main() {
    auto error_code = icu::ErrorCode();
    auto* normalizer = icu::Normalizer2::getNFKDInstance(error_code);
    assert(error_code.isSuccess());
    for (auto test: TESTS) {
        std::string result;
        icu::StringByteSink<std::string> sink(&result);
        normalizer->normalizeUTF8(0, test, sink, NULL, error_code);
        std::cout << "------------------" << std::endl;
        std::cout << "Input: " << test << std::endl;
        std::cout << "Output: " << result << std::endl;
        std::cout << std::endl;
    }

    return 0;
}
```

And compile with:

```bash
`icu-config --cxx --cxxflags --cppflags --ldflags` -o sample sample.cpp
```

The output is as follows:

```bash
------------------
Input: Ｓａｍｐｌｅ　ｔｅｘｔ．
Output: Sample text.

------------------
Input: Ⓢⓐⓜⓟⓛⓔ　ⓣⓔⓧⓣ．
Output: Sample text.

------------------
Input: 𝓢𝓪𝓶𝓹𝓵𝓮 𝓽𝓮𝔁𝓽.
Output: Sample text.

------------------
Input: 𝔖𝔞𝔪𝔭𝔩𝔢 𝔱𝔢𝔵𝔱.
Output: Sample text.

------------------
Input: 𝑺𝒂𝒎𝒑𝒍𝒆 𝒕𝒆𝒙𝒕.
Output: Sample text.

------------------
Input: 𝕊𝕒𝕞𝕡𝕝𝕖 𝕥𝕖𝕩𝕥.
Output: Sample text.
```

**Comment by sthibaul** [comment]
libicu should be fine for a dependency. The codebase for the server is however pure C, I'd rather avoid introducing the C++ dependency just for this, would have a similar code working in C?

**Comment by Alexhuszagh** [comment]
@sthibaul I believe all of this is covered by the C-API, however, personally I've never used it:
https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/unorm2_8h.html

I'll convert the example above to using ICU's C-API.

**Comment by jhenstridge** [comment]
Another alternative would be GLib's `g_utf8_normalize` function:

https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-normalize

It supports both NFKD and NFKC normalizations.
