### ISSUE TITLE
How to change the speed/rate with pico-generic backend?

### ISSUE THREAD

**Issue by liar666** [brailcom/speechd#292]
Hi,

Using Ubuntu 19.10 updated today.

Following the post below, I switched to pico-generic as a backend:
https://webcache.googleusercontent.com/search?q=cache:UWIk0ieinfgJ:https://listengine.tuxfamily.org/lists.tuxfamily.org/carrefourblinux/2011/09/msg00036.html+&cd=9&hl=en&ct=clnk&gl=fr

First, a very strange thing: once the config file changed, speech-dispatcher does not restart. 
There was an error in `/var/log/speech-dispatcher/pico-generic.log` about a connection to pulse that was impossible... I had to swtich to `libao`, other options failed too.
Absolutely no documentation about what the problem is and how to solve it can be found in the doc... Nor why does it happen with pico-generic and not with the default backend.

I tried to change the rate of playback, with the corresponding `DefaultRate` variable in `speechd.conf` but is has no effect. Since I now a way to play a wav file with varying speed, I tried to change the config to use it (./modules/pico-generic.conf):
```
GenericExecuteSynth \
"pico2wave -w $TMPDIR/pico.wav -l $VOICE \'$DATA\' && mplayer -af scaletempo -speed 1.5 $TMPDIR/pico.wav"
```
but that does not change a thing, even after 10ths of restart of the speech-dispatcher daemon...

Also, I would have loved to be able to change the $PLAY variable and use a variable indstead of "1.5", but this does not seem to work... Where and how should I overwrite/configure such variables?

Why are all my changes ignored whereas pico is indeed used as a backend now?

Finally, the configuration of the rate thing should be corrected, there are plenty of tools in linux (mplayer/sox) to change the rate of pico's generated file a posteriori...

**Comment by sthibaul** [comment]
Hello,
It is not recommended to use the pico-generic module, which has indeed very limited ability to control how pico behaves, how the playback behaves, etc. Actually we whould probably just remove it.
It is way preferrable to use the pico module, which can have a fine-grain control over the synthesis, and achieves the playback like all other non-generic modules, which through whatever alsa/pulse/libao supported backend. Please make a try with it.

**Comment by liar666** [comment]
OK I tried pico rather than pico-generic, but when I do `service speech-dispatcher restart`, I get:

```
# tail /var/log/speech-dispatcher/speech-dispatcher.log
[Fri Apr  3 00:13:46 2020 : 434660] speechd:   Speech Dispatcher started with 1 output module
[Fri Apr  3 00:13:46 2020 : 435222] speechd: Speech Dispatcher started and waiting for clients ...
[Fri Apr  3 00:13:51 2020 : 476428] speechd: Terminating...
[Fri Apr  3 00:13:51 2020 : 476496] speechd:  Closing open connections...
[Fri Apr  3 00:13:51 2020 : 477191] speechd:  Closing open output modules...
[Fri Apr  3 00:13:51 2020 : 477234] speechd:   Unloading module name=pico
[Fri Apr  3 00:13:51 2020 : 477266] speechd:   Closing module "pico"...
[Fri Apr  3 00:13:51 2020 : 477605] speechd: ERROR: waitpid() failed when waiting for child (module).
[Fri Apr  3 00:13:51 2020 : 477637] speechd:  Closing server connection...
[Fri Apr  3 00:13:51 2020 : 477688] speechd:  Speech Dispatcher terminated correctly
```
It's the same when stoping/starting the service...
I don't understand why (re)starting leads to "correct termination"?? Should rather be started and running infinitely like any daemon, no?

**Comment by sthibaul** [comment]
Please check the pico.log file, it'll tell you why the module died.

**Comment by liar666** [comment]
OK, I've added debugging in `pico.conf` and I have:

```
# cat /var/log/speech-dispatcher/pico.log 
 Fri Apr  3 00:27:17 2020 [317739]: Using libao audio output method
 Fri Apr  3 00:27:17 2020 [318038]: CMD: <LOGLEVEL
>
 Fri Apr  3 00:27:22 2020 [477492]: CMD: <STOP
>
 Fri Apr  3 00:27:22 2020 [477562]: pico: STOP called when not in PLAY state
 Fri Apr  3 00:27:22 2020 [477599]: CMD: <QUIT
>
```

Changing the libao to anything else does not work... For instance, using pulse (which is installed and working on my machine):
```
# cat /var/log/speech-dispatcher/pico.log 
 Fri Apr  3 00:28:49 2020 [499471]: Configuration (pre) has been read from "/etc/speech-dispatcher/modules/pico.conf"

 Fri Apr  3 00:28:49 2020 [499616]: pico: Playback thread starting
 Fri Apr  3 00:28:49 2020 [503802]: CMD: <AUDIO
>
 Fri Apr  3 00:28:49 2020 [503951]: Opening audio output system
pulse.c: pa_simple_new() failed: Connection refused
```

So speech-dispatcher is just totally unusable with pico here...

**Comment by sthibaul** [comment]
Did you configure pulseaudio to work as a system root-started service? Otherwise it will refuse speech-dispatcher using pulseaudio as root.

**Comment by liar666** [comment]
Thanks for your answers...

Pulseaudio is apparently started as user (I didn't configure it, so it's my distribution's - XUbuntu - choice... which is quite good from a security point of view...).

Apparently playing with speech-dispatcher has totally broken pulseaudio... I cannot play any sound now...
There's a defunct pulseaudio process that I cannot kill and that is attached to systemd... So I apparently cannot repair that without rebooting :{

**Comment by sthibaul** [comment]
but I'm wondering: why do you start speech-dispatcher as a system daemon?

**Comment by sthibaul** [comment]
(that's not the default way of using it)

**Comment by sthibaul** [comment]
(and yes, running pulseaudio as root is frowned upon in general, for various reasons)

**Comment by liar666** [comment]
> (that's not the default way of using it)

I was just following a tutorial :)

**Comment by sthibaul** [comment]
Beware of tutorials :) They often recommend dangerous things

**Comment by sthibaul** [comment]
(btw I can confirm that the pico module normally works with libao as well as with pulse)
