### ISSUE TITLE
Support for gender sensitive language

### ISSUE THREAD

**Issue by joanmarie** [brailcom/speechd#296]
There have now been two bugs filed against Orca for this feature:
* https://gitlab.gnome.org/GNOME/orca/-/issues/113
* https://gitlab.gnome.org/GNOME/orca/-/issues/23

As I've stated in the first of the above:
> I'm not sure how I can solve this in Orca. Orca doesn't have a dictionary in which it stores all possible words for all languages which might need to be pronounced in a different fashion. Instead, gets strings (e.g. from web page content, LibreOffice documents, email messages, etc., etc.). Then it sends those strings to speech-dispatcher which in turn sends them to language-specific speech synthesizers (e.g. espeak, voxin, etc.). Thus I think the place to fix this would either be in speech-dispatcher or the synthesizers.

I stated something similar in the second of the above:
> I think is important to keep in mind is that a screen reader's job is to present what is on the screen. If "nosotrxs" is on the screen, I do not think the screen reader (i.e. Orca) should modify that text turning it into, say, "nosotros" or "nosotros o nosotras" or anything else.
>
> If an optional layer is called for, perhaps it could live in Speech Dispatcher so other tools which include text-to-speech functionality (such as the NVDA screen reader) could also benefit from it?

Thoughts?

**Comment by sthibaul** [comment]
That would be much more a job for speech-dispatcher than Orca indeed.
Ideally it'd be a job for speech syntheses, but I guess it's useful to have a coherent behavior in speech-dispatcher (that one could disable, in case the speech synthesis being used does a better job).

- 113 talks about German, in which `Leser*innen` or `Leser_innen` should ve replaced with `Leser Innen`
- 23 talks about Spanish, in which `nosotrxs` or `nosotres` should be replaced by `nosotros` .
- In French, we have `auteur(e)` or `auteur·e`, but also `directeur·trice`.

Actually, the .dic support that is to be released with version 0.10 can possibly allow to write some rules to rewrite these before the synth. I'd then be a matter for people to contribute them for their language specificities.
