### ISSUE TITLE
Speech-dispatcher wouldn't use Festival properly

### ISSUE THREAD

**Issue by OakLD** [brailcom/speechd#299]
Hello,

I have Festival set, it works and it also receives and plays sound when server is running:

`nc localhost 1314 <<< "(tts_text \"Hello big world, this is a test.\" nil)(quit)"`

 then configured speech-dispatcher, it failed to properly configure itself via spd-conf, but I manually fixed the configuration `filespeechd`. To sum it up:

```LogLevel  3
LogDir  "default"
DefaultRate  5
DefaultVolume 100    
DefaultLanguage "en"
DefaultPunctuationMode "all"
AudioOutputMethod "alsa"
AudioALSADevice "default"
AddModule "festival"     "sd_festival"  "festival.conf"
AddModule "dummy"         "sd_dummy"      ""
DefaultModule festival
LanguageDefaultModule "en"  "festival"
Include "clients/*.conf"
```

Next, ALSA test is working fine (producing sound). However, when I send a text to speech-dispatcher:

`spd-say "Hello big world, this is a test."`

...the festival server goes crazy, like it was unsuccessfully trying each and every voice it can think of:

```SIOD: unknown voice cmu_us_ahw_cg
SIOD: unknown voice cmu_us_ahw_cg
SIOD: unknown voice cmu_us_aup_cg
SIOD: unknown voice cmu_us_aup_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_axb_cg
SIOD: unknown voice cmu_us_axb_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD ERROR: could not open file /usr/share/festival/dicts/oald/oaldlex.scm
closing a file left open: /usr/share/festival/voices/english/rab_diphone/festvox/rab_diphone.scm
SIOD: unknown voice rab_diphone
SIOD ERROR: could not open file /usr/share/festival/dicts/oald/oaldlex.scm
closing a file left open: /usr/share/festival/voices/english/rab_diphone/festvox/rab_diphone.scm
SIOD: unknown voice rab_diphone
SIOD: unknown voice cmu_us_kal_com_hts
SIOD: unknown voice cmu_us_kal_com_hts
SIOD: unknown voice cstr_us_ked_timit_hts
SIOD: unknown voice cstr_us_ked_timit_hts
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD ERROR: ran out of storage 
closing a file left open: /usr/share/festival/voices/us/cmu_us_clb_cg//rf_models/trees_08/cmu_us_clb_mcep.tree
SIOD: unknown voice cmu_us_clb_cg
SIOD ERROR: ran out of storage 
closing a file left open: /usr/share/festival/voices/us/cmu_us_clb_cg//festival/trees/cmu_us_clb_mcep.tree
SIOD: unknown voice cmu_us_clb_cg
client(10) Mon Mar 16 22:10:26 2020 : accepted from localhost
SIOD: unknown voice cmu_us_ahw_cg
SIOD: unknown voice cmu_us_aup_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_axb_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD ERROR: could not open file /usr/share/festival/dicts/oald/oaldlex.scm
closing a file left open: /usr/share/festival/voices/english/rab_diphone/festvox/rab_diphone.scm
SIOD: unknown voice rab_diphone
SIOD: unknown voice cmu_us_kal_com_hts
SIOD: unknown voice cstr_us_ked_timit_hts
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_bdl_cg
SIOD ERROR: ran out of storage 
closing a file left open: /usr/share/festival/voices/us/cmu_us_clb_cg//rf_models/trees_08/cmu_us_clb_mcep.tree
SIOD: unknown voice cmu_us_clb_cg
SIOD ERROR: ran out of storage 
closing a file left open: /usr/share/festival/voices/us/cmu_us_jmk_cg//festival/trees/cmu_us_jmk_mcep.tree
SIOD: unknown voice cmu_us_jmk_cg
SIOD: unknown voice cmu_us_ahw_cg
SIOD: unknown voice cmu_us_ahw_cg
SIOD: unknown voice cmu_us_aup_cg
SIOD: unknown voice cmu_us_aup_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
```

**So, festival is working, connection to ALSA is working, speech-dispatcher is sending something to the festival, but it's somehow broken, possibly wrong voice settings.**

There is also a configuration file for festival module within `/etc/speech-dispatcher/modules/` folder, `festival.conf`, but it's virtually empty (with a lot of commented text) and it does not mention anything about voices set by speech-dispatcher when calling the Festival. It's a place I would assume one can set that, especially because a comment in `speechd.conf`:

> The DefaultVoiceType controls which voice type should be used by default. Voice types are symbolic names which map to particular voices provided by the synthesizer according to the output module configuration. Please see the synthesizer-specific configuration in etc/speech-dispatcher/modules/ to see which voices are assigned to different symbolic names. The following symbolic names are currently supported: MALE1, MALE2, MALE3, FEMALE1, FEMALE2, FEMALE3, CHILD_MALE, CHILD_FEMALE
> 
> \# DefaultVoiceType "MALE1"

I also tried to increase heap size up to 50M (as per some posts in other discussions), but it doesn't help:

`festival --server --heap 50000000`

Any suggestions appreciated.

Versions info:
- Speech-dispatcher 0.8.8-lp151.3.6.1 (from OpenSUSE Leap 15.1 repositories)
- Festival 2.5.0-lp151.1.3 (from OpenSUSE Leap 15.1 repositories)
- festival-freebsoft-utils 0.10-7.el7 (noarch from RL)
- festvox-<xxx>-arctic-hts 2.5.0-3.fc30 (noarch from FC)
- OS OpenSUSE Linux Leap 15.1

**Comment by sthibaul** [comment]
Hello,

I can't reproduce the issue you are having. Speech dispatcher itself doesn't do much with festival except, yes, asking it for the list of supported voices, to be able to show them to speechd clients. Basically it only does

```
nc localhost 1314 <<< "(require 'speech-dispatcher) (apply append (voice-list-language-codes)) (quit)"
```

Could you try just that? If you get the same result, you should report to https://github.com/brailcom/festival-freebsoft-utils instead

**Comment by OakLD** [comment]
Hello, thank you for your effort. I tried to run the command while server is running, the output is following:
```
> nc localhost 1314 <<< "(require 'speech-dispatcher) (apply append (voice-list-language-codes)) (quit)"
LP
t
ft_StUfF_keyOK
```
It doesn't produce any sound, but I'm not sure if it should.

**Comment by sthibaul** [comment]
It's not supposed to, it just asks for the voice list, and apparently that failed since it only acknowledged the first command (require). So the issue is on the festival-freebsoft-utils side.

**Comment by OakLD** [comment]
Thank you very much! I'll dig into installation of the freebsoft-utils and if not successful, I'll try to resolve that with their community or support. Good to know how to check that speech-dispatcher recognises festival voices.

**Comment by ubone** [comment]
How to select festival voice for speech dispatcher to use instead of asking festival for available ones and auto selecting?

I have selected a voice for festival per user and globally but they are ignored and still see:

```
server    Thu Jan 14 19:14:47 2021 : Festival server started on port 1314
client(1) Thu Jan 14 19:14:50 2021 : accepted from localhost
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD ERROR: not a symbol or string : #<CLOSURE n (let-internal (me) (voice_cmu_us_rms_cg) (begin (require "/usr/share/festival/voices/us/cmu_us_rms_cg/festvox/cmu_us_rms_cg") (if (eq me voice_cmu_us_rms_cg) (error (string-append "autoload: "" "/usr/share/festival/voices/us/cmu_us_rms_cg/festvox/cmu_us_rms_cg" ".scm" does not define " (quote voice_cmu_us_rms_cg)))) (apply voice_cmu_us_rms_cg n)))>
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
```

```
spd-say -L
                     NAME                 LANGUAGE                  VARIANT
            cmu_us_slt_cg                     none                     none
            cmu_us_rms_cg                     none                     none
            cmu_us_awb_cg                     none                     none
```

**Comment by ubone** [comment]
ok I see this `spd-say -y cmu_us_rms_cg "something"`

**Comment by aral** [comment]
Seeing the same issue under Fedora Silverblue.

**Comment by sthibaul** [comment]
@aral what probably exactly are you getting?

`SIOD: unknown voice cmu_us_slt_cg`

this rather looks like an issue on the festival server side?
