### ISSUE TITLE
[Feature Request] support isolation of clients with the same user ID

### ISSUE THREAD

**Issue by galgalesh** [brailcom/speechd#335]
According to [the docs about history handling](https://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc/ssip.html#History-Handling-Commands), speechd currently assumes that all clients with the same user ID run inside a single security domain. It allows any client to retrieve the text any other client has asked it to speak since the daemon started, as long as both clients have the same user ID.

Technologies such as [Snap](https://snapcraft.io/) and [Flatpak](https://flatpak.org/) try to improve the security of Linux desktop applications by putting each application in a sandbox with limited, isolated access to the host system. There does not seem to be a secure way to give a sandboxed application access to the speech dispatcher service of the host system because all connected clients have access to the entire history. On a blind person’s desktop this could include every keystroke the user has typed for however long the history log is, assuming key echo is enabled.

As a result, sandboxed applications that use Speech Dispatcher currently bundle it inside of the sandbox, so that each application has its own "private" instance of Speech Dispatcher running. This works more or less, but it has the downside that speech dispatcher cannot coordinate simultaneous messages from multiple apps. When multiple sandboxed apps use Speech Dispatcher at the same time, the text reading overlaps.

In order to solve this issue, I would really like to give sandboxed apps access to the Speech Dispatcher instance of the host. This, however, would require adding a security policy to Speech Dispatcher which is suitable for untrusted clients (don’t leak existence of other clients, block history access or limit it to the client’s own history, etc.)

What are your thoughts on this?

*Note: You can take a look at [the discussion about Text To Speech support in snapd](https://forum.snapcraft.io/t/text-to-speech-support-in-snapd/17099) for more context.*

**Comment by jpwhiting** [comment]
Hey, I agree it would be useful to have more security in speech-dispatcher, but I need to correct you on a couple of points.

A) History. libspeechd.h does have an api to get history, but if you check the implementation, it is unimplemented and has been for quite some time. Ever since 2011 spd_get_message_list returns a string saying it's not implemented yet (I doubt it ever will, especially with the security issues that would introduce).

B) Leaking existence of other clients. Similarly spd_get_client_list isn't implemented in libspeechd.c (Well, there's an implementation there, but it's been commented out since 2006).

From reading the discussion about using speech-dispatcher in snaps, the only issue I see is having it auto launch. I think it would probably be a good step forward for speech-dispatcher to be auto launched by a systemd socket like other daemons already do on demand. That way the host speech-dispatcher with it's configuration would be used by all snaps, but otherwise I think it's already in good shape.

**Comment by sthibaul** [comment]
While reading, without looking at the implementation I was wondering whether any client was actually making any use of this, and whether we could just drop it. If it's not even implemented then that's even easier: we can just drop the templates and the documentation and be done :)

**Comment by galgalesh** [comment]
Thanks a lot @jpwhiting , that's awesome to hear! I'm closing this issue since auto launching doesn't really have to do with isolation.

**Comment by jpwhiting** [comment]
> While reading, without looking at the implementation I was wondering whether any client was actually making any use of this, and whether we could just drop it. If it's not even implemented then that's even easier: we can just drop the templates and the documentation and be done :)

If they are they arent getting anything from these apis. Probably best to just remove them entirely. Bump soname and move on. Good idea.

**Comment by sthibaul** [comment]
> A) History. libspeechd.h does have an api to get history, but if you check the implementation, it is unimplemented and has been for quite some time. Ever since 2011 spd_get_message_list returns a string saying it's not implemented yet (I doubt it ever will, especially with the security issues that would introduce).

Are you sure? `parse_history` does call `history_get_message_list` which does seem to allow looking at the history of other clients.

**Comment by jpwhiting** [comment]
spd_get_message_list_fd in libspeechd.c is implemented to just log
spd_get_client_list: History is not yet implemented." then return -1, but
maybe it's implemented in the python bindings? i.e. maybe there's piping
support for it in the library -> daemon protocol, but the c api at least
isn't using that piping currently or for quite a while. I don't see
anything in api/ that uses parse_history.

**Comment by sthibaul** [comment]
> spd_get_message_list_fd in libspeechd.c is implemented to just log spd_get_client_list: History is not yet implemented." then return -1, but maybe it's implemented in the python bindings?

Well, whether it is implemented in the API libraries is not really what is important. A hacker could just connect to spd by hand without using the library and emit commands.

**Comment by jpwhiting** [comment]
You are right. But since it's not implemented in any of the api libraries
that means nobody is legitimately using the feature so it can be safely and
quietly removed on the server side, no?

**Comment by sthibaul** [comment]
> it can be safely and quietly removed on the server side, no?

Sure, see the recent addition to the TODO

I just mean that for Snap/Flatpak purpose there is currently an isolation issue that needs to be closed along dropping the support in the server.

If somebody could work on that...

**Comment by jpwhiting** [comment]
Ack. Here's my first stab at it.
https://github.com/brailcom/speechd/pull/342
