### ISSUE TITLE
why accept a misspelling

### ISSUE THREAD

**Issue by DidierSpaier** [brailcom/speechd#349]
commit a0baef2b148135bab4105885753e43f97779c131 seems to consider heureu·se·s as a valid orthography. However according to this declaration of the French Academy on the so-called "inclusive writing":  http://www.academie-francaise.fr/actualites/declaration-de-lacademie-francaise-sur-lecriture-dite-inclusive this should be considered as a misspelling.

**Comment by sthibaul** [comment]
I don't care what is "mispelled". What I care of is what people will encounter in the wild life. I have seen "heureu·se·s" in the wild, ergo we want to support it.

**Comment by sthibaul** [comment]
(and I definitely care even less about what academicians would be saying about french, they have never really been or should ever be any kind of authority on what "french" should be. Watch linguisticae videos to know more)
