### ISSUE TITLE
Requested Pulse latency is too low

### ISSUE THREAD

**Issue by YaLTeR** [brailcom/speechd#357]
Fedora 32, speech-dispatcher-0.9.1-6.fc32.x86_64, firefox-78.0.1-1.fc32.x86_64

Opening [Discord](https://discordapp.com) in Firefox spawns speech-dispatcher, which connects to Pulse for playback. However, the latency it requests (500 us) is too low.

![image](https://user-images.githubusercontent.com/1794388/87421394-8a7c4400-c5df-11ea-9ca4-f6b57e0be68a.png)

I have Pulse running with `fixed_latency_range` activated (`load-module module-udev-detect fixed_latency_range=yes` in `/etc/pulse/default.pa`). I need it because of a rhythm game I play: I want the latency to stay constant and never increase. In practice this isn't a problem for any program (because they request a large enough latency), however 500 us requested by speech-dispatcher immediately breaks the audio in most programs.

Could speech-dispatcher request a higher latency? In practice 1000 us seems to already be enough for my PC and I usually play with ~1315 us latency, which doesn't seem to cause any issues with other programs.

**Comment by sthibaul** [comment]
Hello,

Please see https://github.com/brailcom/speechd/issues/198 , which was already fixed in the git for 0.10. You can easily fix with 0.9 by uncommenting

`AudioPulseMinLength 1764`

in speechd.conf.

Samuel

**Comment by YaLTeR** [comment]
Thanks, that has fixed it.
