### ISSUE TITLE
Consider Weblate as translation platform

### ISSUE THREAD

**Issue by rffontenelle** [brailcom/speechd#389]
In my experience, free software project doesn't get much translators  to contribute when they are required to look in the source code of the project to generate or to update the PO file. (I'm an exception, though)

For this reason, I would like to suggest you to consider using a translation platform. As it is an environment that normally voluntaries translate software, it would be easier to get more attention to this project localization.

I feel [Weblate](https://weblate.org) is a great option, as it is gratis for free software, requiring only to have an account be created in Hosted Weblate instance and a request be submitted for the free software to be added. See [this](https://weblate.org/hosting/) page for this information and then [this](https://hosted.weblate.org/hosting/) form (must be logged into Hosted Weblate)

**Comment by sthibaul** [comment]
This is now done on https://hosted.weblate.org/projects/speech-dispatcher/po/ , thanks for the suggestion!
