### ISSUE TITLE
Make the Python API close automatically

### ISSUE THREAD

**Issue by soundmud** [brailcom/speechd#405]
A Python program have to finally call the close() method or it won't quit properly.
Would it be possible to set the thread with daemon=True so it won't  require to call the close() method?

In client.py, line 198:

        self._communication_thread = \
                threading.Thread(target=self._communication, kwargs={},
                                 name="SSIP client communication thread",
                                 daemon=True)

I have tested this with Debian 10 and it works.

Before Python 3.3 it might be necessary to add instead:

        self._communication_thread.daemon = True

**Comment by sthibaul** [comment]
right, thanks!

**Comment by soundmud** [comment]
great, thank you!
