### ISSUE TITLE
Orca Preferences GUI doesn't give access to all availabls spd modules+config

### ISSUE THREAD

**Issue by DidierSpaier** [brailcom/speechd#41]
didier[~]$ ls /usr/lib64/speech-dispatcher-modules/ -1
sd_cicero
sd_dummy
sd_espeak-ng
sd_festival
sd_flite
sd_generic
sd_pico
This list is displayed in the Speech Synthesizer combo box of the  Voice tab of Orca's Preference GUI.
Sounds good, but...
I have also mbrola voices installed, and espeak-ng-mbrola-generic does not appear in the list.
I understand that strictly speaking the module in use is sd_generic, however, this prevents using the mbrola voices in Orca.
However if I uncomment this line in /etc/speech-dispatcher/speechd.conf:
#AddModule "espeak-ng-mbrola-generic" "sd_generic" "espeak-ng-mbrola-generic.conf"
then espeak-ng-mbrola-generic is added to the dop down list in Orca Preferences GUI.

As it would probably too complicated to check for each "module" (actually, module setting)  listed in speechd.conf in if both the synthesizer and at least one voice file are available, maybe just insert in speechd.conf a comment like:

```
# To insure that a module be available in Orca, you need to uncomment
# the corresponding line, removing the leading '#'
# Also, the corresponding  synthesizer should be installed as well as
# at least one voice for it.
```
Maybe that is obvious for everybody but me?

**Comment by sthibaul** [comment]
Well, it's hard to check that voices etc. are available, but checking for the presence of something-generic config files is not too hard or cumbersome, so I just did that.
