### ISSUE TITLE
old info on freebsoft page

### ISSUE THREAD

**Issue by ilyapashuk** [brailcom/speechd#426]
the info on this page:
https://freebsoft.org/doc/speechd/speech-dispatcher.html
should be updated according to new go api

**Comment by cerha** [comment]
Hello, I updated all links at https://freebsoft.org/speechd and added redirection from https://freebsoft.org/doc/speechd to http://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc.

**Comment by sthibaul** [comment]
Heya @cerha ! Thanks for the updates, thus closing
