### ISSUE TITLE
Compiled 0.10.1, hardcoded path to /usr/bin/speech-dispatcher

### ISSUE THREAD

**Issue by maferv** [brailcom/speechd#432]
I downloaded and compiled the source of the 0.10.1 Release, 
Default prefix is /usr/local
But upon trying to start speech-dispatcher I get this error:

  ```
spd-say hi
Failed to connect to Speech Dispatcher:
Error: Can't connect to unix socket /run/user/1000/speech-dispatcher/speechd.sock: Connection refused. Autospawn: Autospawn failed. Spawn error 8: Failed to execute child process “/usr/bin/speech-dispatcher” (No such file or directory)
```

Manually linking /usr/local/bin/speech-dispatcher to /usr/bin/speech-dispatcher solves the issue.

Alternatively, using --prefix=/usr

GNU/Linux

**Comment by sthibaul** [comment]
Make sure to run the libspeechd coming from /usr/local, i.e.:

```
type spd-say
```

to make sure you are getting it from `/usr/local/bin/spd-say`

*and*

```
ldd /usr/local/bin/spd-say
```

to make sure that it's getting its libspeechd from /usr/local/lib.

I guess you are simply missing the call to `ldconfig` after `make install`, it seems that nowadays people most often don't know that they have to do this.
