### ISSUE TITLE
Distortion after speechd spawning when using HDMI output

### ISSUE THREAD

**Issue by marcecj** [brailcom/speechd#446]
Hi,

I've been having this issue for a while now (at least a year) where, when using my HDMI sound output (and *only* then), sound would suddenly become distorted (hard to describe, it sounds glitchy and there's a noticeable left/right delay).  Up to now I just restarted pulseaudio as a workaround, but recently noticed that it always happened when starting KMail.  Following this lead I found out others were having this problem and that it was triggered by speechd auto-spawning (see, e.g., https://bugs.kde.org/show_bug.cgi?id=401493).  Setting `DisableAutoSpawn` in `~.config/speech-dispatcher/speechd.conf` finally caused the issue to go away.

I don't know what *exactly* is causing this, but speechd is as far as I got.  This is with speech-dispatcher 0.9.1 and pulseaudio 13.0 (although I've gone through several different versions of the latter by now).

**Comment by sthibaul** [comment]
This is very probably what was worked around in https://github.com/brailcom/speechd/issues/198 . This is an issue inside pulseaudio which was triggered by the low latency requested by speechd. Please upgrade speech-dispatcher to at least version 0.10.0 to get the work around. Alternatively, uncomment the 

```
AudioPulseMinLength 1764
```
line in `speechd.conf`.

**Comment by marcecj** [comment]
Ah, so this *was* already taken care of in a newer version, guess I need to file a bug with Gentoo to get a newer version in (otherwise I would have tested that first).  Also glad to see there's also a PR for pulseaudio :-) .  Anyway, thanks for the quick response!
