### ISSUE TITLE
PulseAudio backend causes server to underrun in some configurations

### ISSUE THREAD

**Issue by kinetiknz** [brailcom/speechd#45]
I ran into this while investigating Firefox [bug 1444567](https://bugzilla.mozilla.org/show_bug.cgi?id=1444567): on some systems, speech-dispatcher's PulseAudio backend causes the PA server to reconfigure itself for a latency so low that it causes audio in other applications to continuously underrun, effectively breaking normal audio playback.

speech-dispatcher's PA backend configures a 100 byte pa_buffer_attr.tlength here:
https://github.com/brailcom/speechd/blob/master/src/audio/pulse.c#L131

This seems strange - aside from being incredibly small (most systems can't reasonably service a sub-millisecond latency stream), PA expects a computed byte value, but speech-dispatcher's code doesn't account for sample rate, channel count, or sample format changes.  For a typical 44.1kHz stereo f32 stream, a 100 byte tlength ends up requesting a 270 *microsecond* buffer.

Because this pa_buffer_attr is passed to pa_simple_new, there's no opportunity to pass specific pa_stream_flags_t values. The defaults for pa_simple_new include PA_STREAM_ADJUST_LATENCY, which I understand is what causes the server to reconfigure to service the requested latency rather than simply letting the stream's latency float up to the server's normal value.

It seems like speech-dispatcher's PA backend should request a more realistic latency value and scale it correctly for the requested sample rate, channel count, and sample format.  What would break if tlength were set to -1, as the other pa_buffer_attr fields are?  If the intention of low latency streams is to avoid losing buffered audio, the correct solution is to use pa_simple_flush (or, if that doesn't work, a timer to wait for the buffer to flush).

It's not clear what hardware/software/configuration combination causes the PA server to enter this state.  On my Fedora 27 system, I can see speech-dispatcher connecting to PA and requesting unusually low latency streams, but it doesn't cause the PA server to behave badly.  On other systems, such as the user's in the Firefox bug and the other cases I've linked below, PA ends up in a bad state until speech-dispatcher is killed or PA is restarted (effectively disconnecting the s-d streams).  So there's possibly a component a PA bug or misconfiguration at play too.

This has also turned up in other applications, e.g. [Mumble](https://github.com/mumble-voip/mumble/issues/2350) and for an [Ubuntu user](https://launchpad.net/bugs/1736222).

CCing @ford-prefect as a PulseAudio expert in case he has any input on this.

**Comment by Astilex5** [comment]
I'd like to add I've been fighting this to over on the Arch Forums. https://bbs.archlinux.org/viewtopic.php?id=239932
I have a nasty side effect that is akin to crackling. It can be stopped by killing sppech-dispatcher. So far affected apps are Mumble and Discord.

**Comment by JanuszChmiel** [comment]
Dear specialists,
I have The similar issue. When I run ARM 32 bit variant of Speech-dispatcher on Android device. When using Xserver XSDL from Google Play. Espeak speech isbeing interrupted. I have got The following error when typing
spd-say "ahoj kvto"
 user@localhost:/$ *** Error in `/usr/lib/speech-dispatcher-modules/sd_espeak-ng' 
 : double free or corruption (fasttop): 0x0000007f68006510 *** 
Default audio buffer value which is predefined by The creator of Xserver XSDL for his Pulseaudio build in server produces interrupted speech. But if The buffer value is The biggest possible, it can be set in Xserver XSDL settings. Speech interruption is extreme.
So I Am wondering, if would make some sense to recompile Xserver XSDL and decrease The size of audio buffer, or default size is The smallest possible, which makes sense?
Thank you for yours answer.

**Comment by sthibaul** [comment]
Hello,
I see that in Debian the latency was made 20ms instead made 1ms, does it sound more reasonable?
(reported on https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1208826)

**Comment by sthibaul** [comment]
(FTR, we do want a small buffer to get reactivity from desktop action to speech feedback)

**Comment by nifker** [comment]
speech-dispatch still causes audio disruption for me for all applications on an ALC1220 using PA

**Comment by ford-prefect** [comment]
@nifker could you get verbose PulseAudio server logs from when you do this? If it is with recent speech-dispatcher with @sthibaul's fix, please file a bug on https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues
