### ISSUE TITLE
don't hardcode path for SpawnCmd in python api

### ISSUE THREAD

**Issue by ilyapashuk** [brailcom/speechd#463]
please don't hardcode /usr/bin/speech-dispatcher in pathes.py in api/python/speechd but respect system PATH variable instead.

**Comment by sthibaul** [comment]
Why not? That's what spd-say does as well throught libspeechd.

**Comment by ilyapashuk** [comment]
ok, let's make question deeper.
why to hardcode in all apis, not only in python one?
why if user install speechd in custom path, /usr/local/bin for example?
in this particular case we will be able to make symlink, but this not solve problem fully.
why, for example, if speechd is not installed systemvidely, user has'nt admin rights and want to install it on per user bases?

ok, and if idea of using $PATH is so bad for you, why don't make it setable with help of envvars like that:
export SPEECHD_PATH=/mypath

**Comment by sthibaul** [comment]
I still don't understand your use case:

> why to hardcode in all apis, not only in python one?

What did you mean? AFAIK it is currently hardcoded in all speechd apis, so it is coherent.

> why, for example, if speechd is not installed systemvidely, user has'nt admin rights and want to install it on per user bases?

If you want install in a user home, then you can set PYTHONPATH to make python use the bindings installed in the home, and thus auto-launch the daemon installed in the home.

> if idea of using $PATH is so bad for you, why don't make it setable with help of envvars like that:
> export SPEECHD_PATH=/mypath

There is no need for this, PYTHONPATH will already allows to select which python bindings to use.

**Comment by sthibaul** [comment]
That being said, I can understand that it can be convenient on the long run, so I'm pushing support for a SPEECHD_CMD variable, but in your precise use case, you will *need* to use PYTHONPATH to run the new python bindings that take it into account anyway, and that'll happen to already select starting the speech-dispatcher binary installed along that...
