### ISSUE TITLE
Emojis support

### ISSUE THREAD

**Issue by pzajda** [brailcom/speechd#49]
Emojis are more and more used and for the moment, they are hard to read for blind users on Linux.
Implementing emojis support on speechDispatcher could allow to have them supported in every voice supported synthesisers.
A begin of solution could be to use http://cldr.unicode.org/ for the emoji list as NVAccess did for NVDA issue 6523 (nvaccess/nvda#6523) as the emojis list.

**Comment by sthibaul** [comment]
That's also what brltty is considering as a maintained translated source for emoji names, that looks like a good approach to me :)

**Comment by alexarnaud** [comment]
@pzajda Could it possible for you to contextualize more to give us a reason to implement such feature ? Could you give us 2 or 3 concrete tests cases where we could see the lack of the emoji support ?

Best regards,
Alex.

**Comment by pzajda** [comment]
@alexarnaud On social networks, it is not an exception to have emojis in publications; moreover, it can happen we have a link only described by an emoji.

Even some journalists use emojis in their articles, most of the time in the first sentence.

The most important case is on instant messaging; an emoji can change everything for example if someone wants to express sarcasm or to be sure humor or other language precisions are well understood when reading.

Even in some e-mail exchanges it is used to use emojis.

Best regards,

Patrick

**Comment by joanmarie** [comment]
@alexarnaud: Another use case is that Orca would benefit from this support. :smile:

**Comment by pzajda** [comment]
I'm working on a Python script to import emojies from CLDR database.
As discussed on IRC with @sthibaul this script also import NVDA symbols dictionaries to replace the bash script.
For the moment, I only have an unicode character inserted when I append emojies to the dictionary file, which doesn't prevent the dictionary to be processed, emojies are read.
I'm working on fixing it but maybe this is less importent than I think.
Before making a pull request:
* I have to document it
* Also, should we do the same as NVDA, pronounce emojies when punctuations level is set at least to some or everytime?
I think emojies should be pronounced with no minimum punctuation level but this is subjective.

**Comment by sthibaul** [comment]
Note: for Orca to support it, I have just pushed https://github.com/brailcom/speechd/commit/c528da29190261539485211450eb6d11095df597 : so far dictionary was not supported in ssml mode.

**Comment by joanmarie** [comment]
Point of clarification: What I was hoping to do is continue to give the string as-is to speech-dispatcher and have speech-dispatcher recognize emoji characters and speak them correctly. This would also be beneficial because any tool which speaks content through speech-dispatcher would JustWork(tm). Is that the plan?

**Comment by sthibaul** [comment]
Yes, that's the plan :)
