### ISSUE TITLE
some characters are read regardless of punctuation level.

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#529]
## how to reproduce

```bash
$ spd-say -w -m none "— this shouldn't be red on «none or some» punctuation level."
$ spd-say -w -m some "— this shouldn't be red on «none or some» punctuation level."
$ spd-say -w -m all "— this shouldn't be red on «none or some» punctuation level."
```

### what happens

—, « and » read regardless of punctuation level.

### what should be happening instead

—, « and » shouldn't be read at least on none and some. levels.

## information

* distribution - archlinux
* sd version - speech-dispatcher 0.10.2
* config - [sd.txt](https://github.com/brailcom/speechd/files/6211729/sd.txt)
* module - tested on espeak-ng and RHVoice

**Comment by sthibaul** [comment]
For now, by default it's the synthesis module that handles punctuation, so it's the synthesis that would need to be fixed.

As I mentioned in the speech dispatcher 0.10 announce:
“Please try to enable it in speechd.conf by setting SymbolsPreproc to "all" or even "char" instead of "none", and please report any issue with this. In the next release of speech-dispatcher we will set it to at least "all" by default, so that the punctuation experience will be the same whatever the synthesizer being used.”

So SymbolsPreproc has to be set to at least "all" for speech-dispatcher to be responsible for this.

That being said, for the case of —, « and », they have a verbose rule in emojis.dic, that gets before symbols.dic. I would tend to say that possibly we'd rather use symbols.dic before emojis.dic?

**Comment by alex19EP** [comment]
> “Please try to enable it in speechd.conf by setting SymbolsPreproc to "all" or even "char" instead of "none", and please report any issue
I changed SymbolsPreproc to "all".
here are my findings: — is read regardless of level. moreover on most it's read twice.
« and » red by orca on all levels except none, however it isn't read by spd-say on all levels except most

**Comment by sthibaul** [comment]
> I changed SymbolsPreproc to "all".
> — is read regardless of level. moreover on most it's read twice.

Did you also exchange the two lines so that symbols.dic is processed before emojis.dic? (like is now done in master).

**Comment by alex19EP** [comment]
> 
> 
> > I changed SymbolsPreproc to "all".
> > — is read regardless of level. moreover on most it's read twice.
> 
> Did you also exchange the two lines so that symbols.dic is processed before emojis.dic? (like is now done in master).

yes. i compiled latest sd from master.

**Comment by sthibaul** [comment]
I'm not getting these behaviors at all...

Could you set LogLevel to 5 in speechd.conf, make a few tries (with spd-say only for a start) and send me the speech-dispatcher.log?

**Comment by alex19EP** [comment]
> I'm not getting these behaviors at all...
> 
> Could you set LogLevel to 5 in speechd.conf, make a few tries (with spd-say only for a start) and send me the speech-dispatcher.log?

sure [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6219897/speech-dispatcher.log)

**Comment by sthibaul** [comment]
I see that ru/symbols.dic has

—	длинное тире	most	always

which indeed overrides english's default `never` preserve flag. This was introduced by one of

    Ruslan Shukhanov <ru2020slan@yandex.ru>
    Beqa Gozalishvili <beqaprogger@gmail.com>
    Aleksandr Lin'kov <kvark128@yandex.ru>
    alexander Yashin <a.jaszyn@ya.ru>

So please discuss the change with them.

**Comment by sthibaul** [comment]
Concerning `«` and `»` in Orca, this is because for now it still preprocesses them before handing them over to speech dispatcher, as discussed in https://gitlab.gnome.org/GNOME/orca/-/issues/23

**Comment by alex19EP** [comment]
> 
> 
> I see that ru/symbols.dic has
> 
> — длинное тире most always
> 
> which indeed overrides english's default `never` preserve flag. This was introduced by one of
> 
> ```
> Ruslan Shukhanov <ru2020slan@yandex.ru>
> Beqa Gozalishvili <beqaprogger@gmail.com>
> Aleksandr Lin'kov <kvark128@yandex.ru>
> alexander Yashin <a.jaszyn@ya.ru>
> ```
> 
> So please discuss the change with them.

but these dictionaries are taken from nvda right? can we fix this in SD?

**Comment by sthibaul** [comment]
> but these dictionaries are taken from nvda right?

Yes, but I'd rather not maintain them in speech-dispatcher, we don't have the same manpower as nvda.

**Comment by alex19EP** [comment]
> 
> 
> > but these dictionaries are taken from nvda right?
> 
> Yes, but I'd rather not maintain them in speech-dispatcher, we don't have the same manpower as nvda.

ok but NVDA doesn't read —. I tested it now.

**Comment by sthibaul** [comment]
> ok but NVDA doesn't read —. I tested it now.

?? I don't see how that can be, given the rule in place, which explicitly says "always preserve the symbol".

**Comment by alex19EP** [comment]
> 
> 
> Concerning `«` and `»` in Orca, this is because for now it still preprocesses them before handing them over to speech dispatcher, as discussed in https://gitlab.gnome.org/GNOME/orca/-/issues/23

@joanmarie can you do something about this? It is very uncomfortable.

**Comment by sthibaul** [comment]
> > > but these dictionaries are taken from nvda right?
> > 
> > 
> > Yes, but I'd rather not maintain them in speech-dispatcher, we don't have the same manpower as nvda.
> 
> ok but NVDA doesn't read —. I tested it now.

Do you have Unicode emoji support enabled?

**Comment by alex19EP** [comment]
> 
> 
> > > > but these dictionaries are taken from nvda right?
> > > 
> > > 
> > > Yes, but I'd rather not maintain them in speech-dispatcher, we don't have the same manpower as nvda.
> > 
> > 
> > ok but NVDA doesn't read —. I tested it now.
> 
> Do you have Unicode emoji support enabled?

yes.

**Comment by sthibaul** [comment]
> > > > > but these dictionaries are taken from nvda right?
> > > > 
> > > > 
> > > > Yes, but I'd rather not maintain them in speech-dispatcher, we don't have the same manpower as nvda.
> > > 
> > > 
> > > ok but NVDA doesn't read —. I tested it now.
> > 
> > 
> > Do you have Unicode emoji support enabled?
> 
> yes.
> 
> tested with CLDR disabled doesn't make a difference.

Then I don't see how NVDA can be not saying it, since it's an "always preserve", and the cldr dictionary is supposed to pronounce it...
Anyway, we planned to prune our emojis dictionaries from non-emoji characters, that should be avoiding the pronounciation even with the "always preserve" flag.

**Comment by sthibaul** [comment]
> Anyway, we planned to prune our emojis dictionaries from non-emoji characters, that should be avoiding the pronounciation even with the "always preserve" flag.

Please retry with the latest master

**Comment by alex19EP** [comment]
> > Anyway, we planned to prune our emojis dictionaries from non-emoji characters, that should be avoiding the pronounciation even with the "always preserve" flag.
> 
> Please retry with the latest master

yes. — is fixed. will wate @joanmarie answer regarding quotes problem.

**Comment by joanmarie** [comment]
Sorry. Could you please tell me specifically what the "quotes" problem is that we're trying to fix? Could you give me a debug.out showing me the specific characters Orca is pre-processing and the context in which it is doing so? Thanks!

**Comment by alex19EP** [comment]
> Sorry. Could you please tell me specifically what the "quotes" problem is that we're trying to fix? Could you give me a debug.out showing me the specific characters Orca is pre-processing and the context in which it is doing so? Thanks!

sure. [debug-2021-03-30-17:53:23.out.txt](https://github.com/brailcom/speechd/files/6229913/debug-2021-03-30-17.53.23.out.txt)

i looked at line: ($ spd-say -w -m none "— this shouldn't be red on «none or some» punctuation level.") on this page.

orca reads «» even on some punctuation level.

**Comment by joanmarie** [comment]
Aha. I'd accept a merge request from @sthibaul to fix that for you. :smile:

**Comment by sthibaul** [comment]
Well, I would say that this is the chnames clean-up mentioned in https://gitlab.gnome.org/GNOME/orca/-/issues/23, which is actually waiting for speech-dispatcher 0.11 to be more widespread.

That being said, orca has in punctuation_settings.py:

```
punctuation[left_double_angle]  =  [ LEVEL_NONE, PUNCTUATION_REPLACE ]
punctuation[right_double_angle] =  [ LEVEL_NONE, PUNCTUATION_REPLACE ]
```

Possibly we want to just turn them to LEVEL_MOST like the other quotes?

**Comment by joanmarie** [comment]
That sounds reasonable to me.
