### ISSUE TITLE
slow responce on latest master

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#535]
## how to reproduce

1. run orca
2. open the terminal (I used mate terminal)
3. fill it quickly with text. (I used dmesg for that)

## what happening

the speech does not immediately silents  if you press the control. if you try to use a flat review the reaction is slow.

## what should happen

everything should be as fast as before.

**Comment by sthibaul** [comment]
which speech synthesis are you using?

Ideally, you'd be able to git bisect, to determine what introduce the issue.

**Comment by alex19EP** [comment]
> which speech synthesis are you using?

espeak-ng

> Ideally, you'd be able to git bisect, to determine what introduce the issue.

if you realy need this - I can do it. but I'm pretty sure it was audio refactoring.

**Comment by sthibaul** [comment]
> > which speech synthesis are you using?
> 
> espeak-ng

Ok, I'm not seeing any such kind of issue :/

> > Ideally, you'd be able to git bisect, to determine what introduce the issue.
> 
> if you realy need this - I can do it. but I'm pretty sure it was audio refactoring.

Sure, but which part, that's the question.

**Comment by alex19EP** [comment]
> Ideally, you'd be able to git bisect, to determine what introduce the issue.

I think 7d5d392308138d0e9ddcaf3ea6d163977fb6bb5a is the first bad commit

just in case, here's my logs: [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6229842/speech-dispatcher.log)

i executed sudo dmesg then tried to silence speech with ctrl and used flat review.

**Comment by sthibaul** [comment]
> > Ideally, you'd be able to git bisect, to determine what introduce the issue.
> 
> I think [7d5d392](https://github.com/brailcom/speechd/commit/7d5d392308138d0e9ddcaf3ea6d163977fb6bb5a) is the first bad commit

That's a bit old and had another bug, fixed in between by 226404ec66d6001daa6f89aa36e7a19c07179589.

Does 16dc1c0d72d813ad9ee811eea22b1bd1fa182dba already have the issue?

**Comment by sthibaul** [comment]
> just in case, here's my logs: [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6229842/speech-dispatcher.log)
> 
> i executed sudo dmesg then tried to silence speech with ctrl and used flat review.

Thanks, it's very informative, it seems the audio flushing is not happening that well on your system indeed. Could you please still try 16dc1c0d72d813ad9ee811eea22b1bd1fa182dba, 476d938eaab11c397e03f2e3cc3142b56cb22a17 and f13f7260a23c834a87cf34e71f89ffb88a2327c9 ?

**Comment by alex19EP** [comment]
> > just in case, here's my logs: [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6229842/speech-dispatcher.log)
> > i executed sudo dmesg then tried to silence speech with ctrl and used flat review.
> 
> Thanks, it's very informative, it seems the audio flushing is not happening that well on your system indeed. Could you please still try [16dc1c0](https://github.com/brailcom/speechd/commit/16dc1c0d72d813ad9ee811eea22b1bd1fa182dba), [476d938](https://github.com/brailcom/speechd/commit/476d938eaab11c397e03f2e3cc3142b56cb22a17) and [f13f726](https://github.com/brailcom/speechd/commit/f13f7260a23c834a87cf34e71f89ffb88a2327c9) ?

i tried 16dc1c0 it worked ok. do i need to try 476d938 and f13f726 ?

**Comment by sthibaul** [comment]
The espeak-ng.log with Debug enabled in espeak-ng.conf, would also be very welcome.

**Comment by alex19EP** [comment]
f13f726 is bad.

476d938e works very strange. and I cannot repeat the steps causing the problem.
it seems to me that the orca is simply ignoring some chunks of the text.

**Comment by sthibaul** [comment]
> > The espeak-ng.log with Debug enabled in espeak-ng.conf, would also be very welcome.
> 
> on witch commit?

Latest master should be fine.

**Comment by alex19EP** [comment]
i recorded it on f13f7260 hope you don't mind.

[logs.tar.gz](https://github.com/brailcom/speechd/files/6240125/logs.tar.gz)

**Comment by alex19EP** [comment]
executed sudo dmesg and tried to press ctrl and numpad keys.

**Comment by sthibaul** [comment]
> i recorded it on [f13f726](https://github.com/brailcom/speechd/commit/f13f7260a23c834a87cf34e71f89ffb88a2327c9) hope you don't mind.

that should be fine

**Comment by sthibaul** [comment]
There was a missing line indeed, could you check with latest master?

**Comment by alex19EP** [comment]
> There was a missing line indeed, could you check with latest master?

problem has been fixed. thanks.
but i have another one :sweat_smile: issue incoming.
