### ISSUE TITLE
No more accent characters pronounced when symbols preprecessing is set to char

### ISSUE THREAD

**Issue by Nardol** [brailcom/speechd#536]
Tested with espeak-NG and Kali.
For example when Orca starts, in French the message is "Lecteur d'écran activé".
Kali pronounces "Lecteur d apostrophe cran active".

Some logs:
* [kali.log](https://github.com/brailcom/speechd/files/6227617/kali.log)
* [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6227618/speech-dispatcher.log)

**Comment by sthibaul** [comment]
This seems to be fixed on my system, could you check?

**Comment by Nardol** [comment]
> This seems to be fixed on my system, could you check?

I confirm the fix, thanks!
