### ISSUE TITLE
sd stops working when orca settings is reloaded

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#541]
## how to reproduce

modify any orca setting and hit OK

## what happening

orca speaks screen reader settings reloaded and stays silent

## what should happen

orca applies settings and speaks as before.

## system info

* orca: 40.0.r17.gd620e58ff-1
* sd: 0.10.1.r198.g703afab1-1
* log: [speech-dispatcher.log](https://github.com/brailcom/speechd/files/6247096/speech-dispatcher.log)

**Comment by sthibaul** [comment]
Ok, there was a long-standing race between listing voices and speak, I ended up cleaning the whole thing up, and I don't have the issue any more.
