### ISSUE TITLE
Freeze when reading a long string with Kali

### ISSUE THREAD

**Issue by Nardol** [brailcom/speechd#542]
Reproduced on each time by typing `ip addr` in mate-terminal using Kali. Using espeak-ng I don't have the freeze.
Nothing is read and I cannot move review cursor (all commands). I have to wait some seconds to be able to use speech-dispatcher again.

Some logs in debug mode:
[kali.log](https://github.com/brailcom/speechd/files/6252296/kali.log)
[speech-dispatcher.log](https://github.com/brailcom/speechd/files/6252297/speech-dispatcher.log)

I started Speech-Dispatcher and typed `ip addr` in mate-terminal.
Then I tried to use review cursor commands, then I activated/deactivated the menu bar until I eared "Fichier".

**Comment by sthibaul** [comment]
Ok, the long messages were indeed keeping the queues hung, splitting them seems to just fix it, could you check?

**Comment by Nardol** [comment]
It is really better, but I notice some unread strings when navigating line by line.
With the same example, if I read the last output line of the ip addr command and I go to the next line, the terminal prompt (in my case `pzajda@pcbob:~ $`) is not spoken.
When navigating word by word it can also occurs.

[kali.log](https://github.com/brailcom/speechd/files/6254109/kali.log)
[speech-dispatcher.log](https://github.com/brailcom/speechd/files/6254110/speech-dispatcher.log)

A strange thing is sometimes, I don't notice this behavior.

**Comment by sthibaul** [comment]
Ok, I got it, the stops when getting misinterpreted. Could you give it another try?

**Comment by Nardol** [comment]
It is perfect now. Thanks!

**Comment by sthibaul** [comment]
Thanks for testing, that's the only way we can find out about bugs!
