### ISSUE TITLE
sound_icon with espeak-mbrola-generic module

### ISSUE THREAD

**Issue by oiseauroch** [brailcom/speechd#549]
# Problem
Sound icon are played only once by speech-dispatcher spawn with espeak-mbrola-generic module

# How to reproduce 
use espeak-mbrola-generic module and use the commande 
```
spd-say -I at && spd-say -I at
```
Sound will be played only once.

It seems to be the same for espeak-ng-mbrola-generic module

**Comment by sthibaul** [comment]
Ok, I see, that should now be fixed in master.
