### ISSUE TITLE
Some strings make Kali crash

### ISSUE THREAD

**Issue by Nardol** [brailcom/speechd#552]
I use a software where I have to set some infrared codes which are base64 encoded and storred in a JSON file.
Some of these codes are very long.
When these very long strings are read by Kali, Speech-Dispatcher switch to the default synth so eSpeak in my case.
To be more precise the line is not read at all, the next spoken thing is read by the default synth.
The example I used in this debug log is: `"JgAcAisMKwwQKBAnEScPKBAnKw0PKBAnEScQAAEFKwwrDQ8oDygQKA8oDygrDQ0qDioNKg4AAQcrDCwMDygQJxAoECcQKCsMECcQKBAnEAABBSwLLAwQJxAnECgQJxAoKwwQJxAoECcQAAEFKg0rDQ4pDykOKQ8oDykpDg4pDykOKQ8AAQYqDioNDygQKBAnECcQKCsMECgQJxAnEAABBSwMKwwQJxAoECcQKBAnLAsQKBAnECgQAAEDLQwrDBAoDygQJxAoDygqDg4pDygPKQ4AAQcpDikODioNKg4qDSoNKikPDSoOKQ4qDQABCCkOKQ8NKg0qDioOKQ8oKw0OKQ8pDygQAAEFKwwsDA8oECcQKBAnECgrDBAnECgQJxAAAQUqDSsNDygQKA8oECcQKCoNDygQKBAnEAABBSsNKwwQJxAoECcQJxAoKwwQKBAnECcQAAEFLAwrDBAnECgQJxAoECcsCxAoECcQJxAAAQUsDCsMECgQJxAnECgQJywMDygQJxAoEAABBSsMLAsQKBAnECcQKBAnLAwQJxAnECgQAAEFKwwsDA8oECcQKBAnECcsDBAnECgQJxAAAQUrDCwMECcQJxAoECcQKCsMECcQKBAnEAABBSwLLAwQJxAoECcQJxAoKwwQJxAoECcQAAEFLAwrDBAnECgQJxAnECgrDBAoECcQJxAAAQUsDCsMECcQKBAnECgPKCkPDQANBQAAAAAAAAAAAAA=",`
If line is wrapped there is no problem but if all characters are on the same line Kali crashes.

[kali.log](https://github.com/brailcom/speechd/files/6332190/kali.log)
[speech-dispatcher.log](https://github.com/brailcom/speechd/files/6332192/speech-dispatcher.log)

I tried also with Voxin which does not crash so it looks like specific to Kali.

**Comment by sthibaul** [comment]
Mmm, according to the log it looks like it is kali itself that crashes. I have added to master a couple of debugging lines to make sure, it does seem it's there. Gdb shows a backtrace deep inside kali.

So I really believe the problem is inside Kali, not in speech-dispatcher.
