### ISSUE TITLE
strange pitch rise when using espeak-ng

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#584]
this issue driving me crazy for a long long time, but only now I found a simple and reliable reproducer for it.

## problem

when orca auto reads system info (email in thunderberd, terminal output, etc)
espeak's pitch will rise and will go higher and higher.

## how to reproduce

I used RHVoice repo for that.
1. clone https://github.com/rHVoice/rHVoice.git
2. instal the nnn terminal file manager.
3. enter rhvoice catalog
4. run nnn -w .
5. move dipper  into src tree.

## what happens

espeak pitch changes.

## what should happen instead

intonation should be same.

## system info

* distribution: Arch Linux
* spd version: 0.10.1.r236.gf1a8725f
* espeak-ng version: 1.50.r328.g467f3f56-1
* sd logs: [logs.tar.gz](https://github.com/brailcom/speechd/files/6487828/logs.tar.gz)

p.s. I have experienced random pitching when using brltty as an sd client.
so i guess this is not an orca problem. but if this is not the case, we can call Joni and I will provide the debug file.

**Comment by sthibaul** [comment]
In the provided log, there is no indication that speech-dispatcher requests a pitch change from espeak. So this rather looks like a bug in espeak-ng itself.

> enter rhvoice catalog

I don't know what that is.

> move dipper into src tree.

I don't know what "dipper" is.

On what actual text is the pitch changing exactly, in the reproduction scenario?

**Comment by alex19EP** [comment]
> In the provided log, there is no indication that speech-dispatcher requests a pitch change from espeak. So this rather looks like a bug in espeak-ng itself.
> 
> > enter rhvoice catalog
> 
> I don't know what that is.

I meant just navigating folders using nnn in a cloned repository.

I think it’s because there are capital letters in the path.

> 
> > move dipper into src tree.
> 
> I don't know what "dipper" is.
> 

sorry for the typo, I mean deeper.

> On what actual text is the pitch changing exactly, in the reproduction scenario?

~/repos/RHVoice/src/android/RHVoice-core/src/main/jni
moreover, the pitch not only changes, but also remains until the SD is restarted

**Comment by sthibaul** [comment]
I don't see anything in the log around this that would mean SD is requesting for a pitch change, so it really looks like an espeak-ng bug.

Does it happen with an english environment?

Ideally, you'd manage to e.g. take from espeak-ng.log the "Requested data:" lines, feed that directly to the espeak-ng command, and reproduce the issue there.

**Comment by alex19EP** [comment]
> I don't see anything in the log around this that would mean SD is requesting for a pitch change, so it really looks like an espeak-ng bug.
> 
> Does it happen with an english environment?
> 

Good catch! after testing it further, I realized that it does not depend on the system locale, but depends on the synthesizer language selected in the orca settings.
for example, if you select American English, this effect is not observed.

> Ideally, you'd manage to e.g. take from espeak-ng.log the "Requested data:" lines, feed that directly to the espeak-ng command, and reproduce the issue there.

can you tell me in more detail how to do this?

**Comment by sthibaul** [comment]
> can you tell me in more detail how to do this?

See in espeak-ng.log the "Requested data:" lines. That's what got sent to espeak-ng. You can try to pass the strings to the espeak-ng command:

```
espeak-ng "some text"
```

and see how it behaves.

**Comment by alex19EP** [comment]
please do not release until we have dealt with this problem.

now sd master is simply not possible to use with espeak-ng if the language of speech is Russian.

I hope tomorrow I will have time to deal with this.

**Comment by alex19EP** [comment]
my observations. looks like wee are hitting another ssml bug in espeak-ng.

@sthibaul i think you can hear the differences without even knoing Russian.

```bash
> espeak-ng -v ru+max -s 380 -m "<speak><mark name="0:6"/>Чтение <mark name="7:8"/>с <mark name="9:15"/>экрана <mark name="16:25"/>включено.<mark name="__spd_0"/></speak>"
```

pay attention to the rise of the intanation at the end.

if i remove last ssml tag:

```bash
> espeak-ng -v ru+max -s 380 -m "<speak><mark name="0:6"/>Чтение <mark name="7:8"/>с <mark name="9:15"/>экрана <mark name="16:25"/>включено.</speak>"
```

everything is pronounced normally.

**Comment by sthibaul** [comment]
Ok, could you raise it to the espeak-ng project?

**Comment by alex19EP** [comment]
> Ok, could you raise it to the espeak-ng project?

I'm afraid I won't be able to explain it well to them ...
can you do this?

also I'm interested. why this problem didn't appear until version 11.

**Comment by sthibaul** [comment]
That being said I'm surprised that you seem to be saying that this is specific to speechd 0.11? The code that adds such marks has not changed for years. Maybe you can check in the logs of versions of speechd with and without the issue, to look for `MSG altering 2:` messages, which is where the `__spd_0` mark is added.

**Comment by sthibaul** [comment]
> I'm afraid I won't be able to explain it well to them ...

Just like you did, actually, you can even reduce to

`espeak-ng -v ru+max -s 380 -m "<speak>включено.<mark name=foo/></speak>"`

raises pitch while

`espeak-ng -v ru+max -s 380 -m "<speak>включено.</speak>"`

does not.

**Comment by alex19EP** [comment]
> > I'm afraid I won't be able to explain it well to them ...
> 
> Just like you did, actually, you can even reduce to
> 
> `espeak-ng -v ru+max -s 380 -m "<speak>включено.<mark name=foo/></speak>"`
> 
> raises pitch while
> 
> `espeak-ng -v ru+max -s 380 -m "<speak>включено.</speak>"`
> 
> does not.

ok. will do.

**Comment by alex19EP** [comment]
> > I'm afraid I won't be able to explain it well to them ...
> 
> Just like you did, actually, you can even reduce to
> 
> `espeak-ng -v ru+max -s 380 -m "<speak>включено.<mark name=foo/></speak>"`
> 
> raises pitch while
> 
> `espeak-ng -v ru+max -s 380 -m "<speak>включено.</speak>"`
> 
> does not.

ok. will do.

> That being said I'm surprised that you seem to be saying that this is specific to speechd 0.11? The code that adds such marks has not changed for years. Maybe you can check in the logs of versions of speechd with and without the issue, to look for `MSG altering 2:` messages, which is where the `__spd_0` mark is added.

now I feel very stupid. i checked rc version of speech-despatcher on another computer. and then everything is ok ...
it seems not as easy as I thought before.

**Comment by sthibaul** [comment]
> I feel very stupid

The only stupid people are the people who refuse to check twice what they are doing. We all make mistakes, that's why we all cross-check and ask other people check what we are doing. That's the very reason for my asking for testing rc1 ;)

> on another computer. and then everything is ok

S onow you have two situations where it works on one side and it doesn't on the other. You can probably work down the difference by comparing logs etc.

**Comment by alex19EP** [comment]
> 
> S onow you have two situations where it works on one side and it doesn't on the other. You can probably work down the difference by comparing logs etc.

ok on my main system in /etc/speech-dispatcher/modules/espeak-ng.conf
parameter `EspeakCapitalPitchRise` was somehow set to 3

I don’t know what this parameter means and I don’t even know is 3 a normal value?

I set it to default 0 for now.

I do not understand why this error occurs with this parameter, but not without it. well, and also I do not understand why espeak-ng has a problem with ssml, but without this parameter it does not appear in sd.

**Comment by alex19EP** [comment]
> Ok, could you raise it to the espeak-ng project?

created espeak-ng/espeak-ng#975

**Comment by sthibaul** [comment]
3 is a normal value for `EspeakCapitalPitchRise`: it means expressing capital letters through a pitch rise.
Pitch rise accumulating however still seems like a bug, in espeak-ng again most probably.

**Comment by alex19EP** [comment]
> 3 is a normal value for `EspeakCapitalPitchRise`: it means expressing capital letters through a pitch rise.

ok thanks for info. in fact, I realized that this problem was a long time ago. just with a parameter of 0 it is very difficult to notice it, but now I listen to espeak and notice small rises and falls in intanation.

> Pitch rise accumulating however still seems like a bug, in espeak-ng again most probably.

I think so ... let's wait for what upstream will answer.
