### ISSUE TITLE
spd-say cuts off each time after 4 seconds of speech

### ISSUE THREAD

**Issue by ChickenKiddie** [brailcom/speechd#590]
It cuts off with default module and voice. It cuts off the same when adding custom  '-o rhvoice' flags. Command-line spd-say command always cuts off after 4 seconds of speech. Using the most up-to-date libraries on arch pacman -Syu.

**Comment by sthibaul** [comment]
Try with `-w` ?

**Comment by ChickenKiddie** [comment]
`-w` helped, thank you @sthibaul

**Comment by ernstki** [comment]
Are there circumstances which could prevent the entire piped input from reaching the speech synthesizer, leading to the situation reported here? Maybe high system load?

Weirdly, I'm unable to reproduce this right now, which leaves me even more confused, but what _had_ been happening is I'd pipe the CLIPBOARD or PRIMARY selection to `spd-say -e` and I'd only hear a few seconds of audio.  [This Ask Ubuntu question](https://askubuntu.com/questions/1165567/why-does-spd-say-stop-speaking-after-a-short-while-in-the-command-line) (and [this one](https://askubuntu.com/questions/1264967/speech-dispatcher-stopped-working-spd-say-starts-but-stops-after-a-few-words)) mentions a similar problem, and others made the same suggestion to use `-w`, with no real explanation of why `spd-say` would drop part of its input in pipe mode without it.

Perhaps it's a downstream packaging problem (I'm using an Ubuntu LTS release), or a strange corner case that only a few people are triggering?

**Comment by sthibaul** [comment]
> Are there circumstances which could prevent the entire piped input from reaching the speech synthesizer, leading to the situation reported here? Maybe high system load?

No. Even on high load the pipeline will stay there, with spd-say reading line by line and pushing to speech-dispatcher.

**Comment by sthibaul** [comment]
and without -w it will just push to speech-dispatcher and only wait for it to confirm that it has received the messages to be spoken

**Comment by ernstki** [comment]
Right, that's what I finally realized with your earlier response. Thanks for your patience.

I honestly thought that there was some _reason_ `spd-say -e` would disregard the majority of its input. The accepted Ask Ubuntu answer [here](https://askubuntu.com/questions/1165567/why-does-spd-say-stop-speaking-after-a-short-while-in-the-command-line) says `spd-say` might exit early "if the text is too long," but that doesn't sound like the intended behavior at all.

I'll increase the log level for my `speech-dispatcher` and keep an eye on it. Maybe it's something distro-specific.
