### ISSUE TITLE
spd-say mangles non-ASCII characters, mostly turning them into question marks

### ISSUE THREAD

**Issue by vermeeren** [brailcom/speechd#594]
I am attempting to add a custom generic output for a language containing more than base ASCII. As it was not working as expected I decided to test running the to-be-spoken speech through `kdialog`, which pops up a GUI window with the contents.

**modules/test-generic.conf**

```conf
GenericExecuteSynth "kdialog --msgbox \'$DATA\'"
GenericCmdDependency "kdialog"
```

Then I execute in a terminal with proper UTF-8 locale: `spd-say 'abc é á あ 日本語 한국어'`

![Screenshot_20210710_041941](https://user-images.githubusercontent.com/5957454/125148931-0dbe7000-e136-11eb-9da2-3fbe6cc10beb.png)

Running the program directly causes no such issues: `kdialog --msgbox 'abc é á あ 日本語 한국어'`

![Screenshot_20210710_042002](https://user-images.githubusercontent.com/5957454/125148951-33e41000-e136-11eb-9e6c-1b2e34797c71.png)

Is it possible to disable or change this behaviour so that the characters are passed through? I have checked the documentation but could not find a solution.

I am running with official Debian packages on Debian bullseye, which is currently version 0.10.2.

Thanks!

**Comment by sthibaul** [comment]
Hello,

When I try to use `GenericExecuteSynth "kdialog --msgbox \'$DATA\'"` in `espeak-ng-mbrola-generic.conf`, the dialog shows up fine.

Please enable 

```Debug 1```

in your config file and look at the generated log file, to see what is actually happening.

Please also post your configuration file, I do not have a cristal bal to be able to read it. I can only guess that your `GenericLanguage` character encoding specification is wrong for the locale that spd-say happens to end up with. Again, the log will tell us.

**Comment by vermeeren** [comment]
@sthibaul Thanks for the quick reply, I appreciate it!

I ran it in debug mode with `speech-dispatcher -s -D -t 0` and indeed the logs in /tmp have the conversion warning, after explicitly adding all the language lines it's working nicely, example:

```
GenericLanguage "en" "english" "UTF-8"
```

The newly added documentation looks good to me too.

Cheers!
