### ISSUE TITLE
locale short code for using Arabic with Festival within Orca

### ISSUE THREAD

**Issue by linuxscout** [brailcom/speechd#596]
Salam,
I try to configure Arabic Festival voice with Orca, 
On the Screen Reader preferences: 
* I use a locale "ar-DZ", but my voice is listed under "en" language list.
Can I have help to do fix this
Thanks

**Comment by sthibaul** [comment]
Hello,
Which arabic language do you have working in festival? I don't know any
Samuel

**Comment by linuxscout** [comment]
Hello,
I used  [Arabic Voice for festival](https://github.com/linuxscout/festival-tts-arabic-voices )

There is one Arabic language, the voice is mentionned as "arabic" only,

but, the locales use LANG + COUNTRY-CODE: like (Arabic algeria is ar-DZ)

Thanks

**Comment by linuxscout** [comment]
When I run festival with command
```
festival --language arabic
```
it works, but within Orca Preferences, it missplace the voice within language

Thanks

**Comment by sthibaul** [comment]
Ok, it seems it is an issue in the arabic festival package itself: speech-dispatcher's festival.log says:

```
Sat Jul 24 19:15:34 2021 [455160]: Voice list reply: |(kal_diphone en US ara_norm_ziad_hts en US lp_diphone it nil pc_diphone it nil)|
```

So it's festival itself which is saying that `ara_norm_ziad_hts` is for the `en_US` locale. Please report the issue there, speech-dispatcher is only rightfully following what the arabic festival package is saying.

**Comment by linuxscout** [comment]
Thank you

**Comment by linuxscout** [comment]
How can I get this log:
Sat Jul 24 19:15:34 2021 [455160]: Voice list reply: |(kal_diphone en US ara_norm_ziad_hts en US lp_diphone it nil pc_diphone it nil)|

**Comment by sthibaul** [comment]
Set `Debug 1` in festival.conf, and re-run speech-dispatcher.
