### ISSUE TITLE
sd_dummy dumps core

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#605]
## repro steps

```
~ /usr/lib/speech-dispatcher/speech-dispatcher-modules/sd_dummy /etc/speech-dispatcher/modules/dummy.conf  
```

## what happening

```
Error opening configuration file '/etc/speech-dispatcher/modules/dummy.conf'
[1]    21631 segmentation fault (core dumped)  /usr/lib/speech-dispatcher/speech-dispatcher-modules/sd_dummy 
```

## what should happen

module should start.

## other info

indeed config in /etc/speech-dispatcher/modules/dummy.conf
doesn't exist and as far as I know it doesn't exist in src tree either.

## environment info

* os: arch linux
* sd version: speech-dispatcher-git 0.11.0.rc2.r9.g7abe107c-1

**Comment by alex19EP** [comment]
also with the module `/ usr / lib / speech-dispatcher / speech-dispatcher-modules / sd_cicero` the same thing happens, but I'm not sure if this is a bug.

arch doesn't package cicero so maybe I should just not build this module?

**Comment by sthibaul** [comment]
I cannot reproduce the issue, I'm getting

```
$ /usr/local/libexec/speech-dispatcher-modules/sd_dummy /etc/speech-dispatcher/modules/dummy.conf
Error opening configuration file '/etc/speech-dispatcher/modules/dummy.conf'
```

which is indeed expected. Could you run it inside gdb, to get a backtrace with `bt all` ?

**Comment by alex19EP** [comment]
sure: https://asciinema.org/a/6zVW5dE9YUnQVWxygUgTA0hZS

I hope I did everything right.

**Comment by sthibaul** [comment]
This is so odd.

Could you create a `dummy.conf` file containing

```
Debug 1
```

so we get information in `dummy.log` ?

I guess possibly something like your environment putting some constraints that make the modules not even able to create threads (?!)
