### ISSUE TITLE
Generic configuration files aren't supported in Firefox

### ISSUE THREAD

**Issue by Shallowmallow** [brailcom/speechd#606]
Hi !

For example if you use pico.conf, it works perfectly in firefox .
But when you use the generic version , it doesn't . Why is that ?

Is it because speechd sends directly the wav file to firefox ? Is there a way to make a generic configuration work in Firefox ?

**Comment by sthibaul** [comment]
Hello,

I'm afraid I don't understand what you mean by "in firefox". What are you doing exactly?

Speech-dispatcher doesn't currently support sending wav to clients, it implements audio rendering itself (either in the module itself, or in the speech-dispatcher server)

Note that to get debugging information you can increase `LogLevel` to 5 in `speechd.conf`, and enable per-module debugging with `Debug` in `pico-generic.conf`, and you'll see the logs in `/run/user/$UID/speech-dispatcher/log`

**Comment by Shallowmallow** [comment]
In fact, firefox uses speech-dispatcher when you use tts. For some reason, it works perfectly with pico.conf  but not with the generic versions .
For example if you click on "j'écoute" here  https://pragmatice.net/pragmactivites/orthodefi/app/?epe&101  , it doesn't work with the generic version of pico, but works with the normal version.

Thanks for the tip :)

**Comment by mothsART** [comment]
I have the same issue for an other case.
I try to interface (with generic) the TTS gSpeech (maintain here : https://github.com/mothsART/gSpeech, python langage) with speech-dispatcher.

I create this module file :

```code
GenericExecuteSynth "gspeech-cli -i \'$DATA\' -o /tmp/sound.wav && play /tmp/sound.wav"
GenericCmdDependency "gspeech-cli"
```
and activate on **speechd.conf** :+1: 

```code
DefaultModule gspeech-cli-generic
```

If I used :

```code 
spd-say "Un parent de la famille se sert du bacon et un yaourt"
```

Reading works well with gSpeech.

But, same issue on Firefox than @Shallowmallow
I am unable to know if the problem comes from Firefox or from speech-dispatcher.

**Comment by Shallowmallow** [comment]
Just tested the logs.

I have no trace when using firefox and pico-generic. I have traces when using firefox and pico .  Could it mean the problem comes from firefox  ?

**Comment by sthibaul** [comment]
(just as a side note: a simpler and multilanguage test case can be found on  https://mdn.github.io/web-speech-api/speak-easy-synthesis/ )
(for now I can't get it to work at all on my system...)

**Comment by sthibaul** [comment]
Ok, I could fix it on my system. But then I'm getting output completely fine from pico-generic for instance.
So I really need to see the logs you would be able to get.

> I have no trace when using firefox and pico-generic

You mean you have no `.log` file at all?
I don't know how firefox launches speech-dispatcher on your system, but you can check with 

`lsof -p $(pidof speech-dispatcher)`

what log file is used by the particular speech-dispatcher that it happens to be running.

**Comment by Shallowmallow** [comment]
Awesome ! 

Sorry I didn't explain well  . In fact, I had some logs , but when  I tried to use pico-generic with firefox,  it didn't  log anything else , because I had already initialised pico-generic by using spd-say.
If I initialise pico-generic with firefox, I do have some logs which says it has been initialised .

**Comment by sthibaul** [comment]
It seems I'm not explaining well either.

Please post your logs here.

Otherwise I cannot have any clue what is happening, I do not have a cristal ball.

**Comment by Shallowmallow** [comment]
here are my logs ( they have been renamed) :

[speechd.log](https://github.com/brailcom/speechd/files/7165347/speechd.log)
[picogen.log](https://github.com/brailcom/speechd/files/7165349/picogen.log)

**Comment by sthibaul** [comment]
Thanks!
```
[Tue Sep 14 17:03:30 2021 : 893448] speechd:     24:DATA:|SET SELF CLIENT_NAME "who:firefox:web speech api"
| (51)
[Tue Sep 14 17:03:30 2021 : 893493] speechd:     Command caught: "set"
[Tue Sep 14 17:03:30 2021 : 893519] speechd:    Updating client specific settings "who:firefox:web against emacs:*
[Tue Sep 14 17:03:30 2021 : 893657] speechd:     24:REPLY:|208 OK CLIENT NAME SET
|
[Tue Sep 14 17:03:30 2021 : 894017] speechd:     24:DATA:|LIST SYNTHESIS_VOICES
| (23)
[Tue Sep 14 17:03:30 2021 : 894044] speechd:     Command caught: "list"
[Tue Sep 14 17:03:30 2021 : 894083] speechd:     Command sent to output module: |LIST VOICES
| (0)
[Tue Sep 14 17:03:30 2021 : 894277] speechd:     Got 21 bytes from output module over socket
[Tue Sep 14 17:03:30 2021 : 894308] speechd: LINE here:|304 CANT LIST VOICES|
```

Ok, that's why. What is the content of your `pico-generic.conf` file?

**Comment by Shallowmallow** [comment]
It's this ( It didn't work with the default pico-generic.conf, so I added some voices to test as you can see, the fr-FR and fr-fr ones)

`# pico output module is based on the generic plugin for Speech
# Dispatcher. It means there is no code written explicitly for
# this plugin, all the specifics are handled in this configuration
# and we call a simple command line client to perform the actual
# synthesis. Use this config file with the sd_generic output module.
#
# IMPORTANT: The audio output method relies on an audio playback
# utility (play, aplay, paplay for OSS, ALSA or Pulse)
# being installed. If this is not the case, consider installing it
# or replace the $PLAY_COMMAND string in the GenericExecuteString below
# with play, paplay or similar.
#
# GenericExecuteSynth is the shell command that should be
# executed in order to say some message. This command must
# stop saying the message on SIGKILL, otherwise it's useless.
# You can use the variables $LANGUAGE, $VOICE, $PITCH and $RATE
# which will be substituted for the appropriate value (you
# can modify this value, see other parameters).
# The command can be split into more lines, if necessary, using '\'.
GenericExecuteSynth \
"pico2wave -w $TMPDIR/pico.wav -l $VOICE \'$DATA\' && $PLAY_COMMAND $TMPDIR/pico.wav

# The following three items control punctuation levels None, Some, and All.
# Each of these values will be substituted into the $PUNCT variable depending
# on the value passed to speech dispatcher from applications.
# Note that if an empty string is specified, then $PUNCT will be blank 
# which is a default situation for espeak.
 
GenericPunctNone " "
GenericPunctSome "--punct=\"()[]{};:\""
GenericPunctAll "--punct"

# GenericStripPunctChars is a list (enclosed in doublequotes) of
# all the characters that should be replaced by whitespaces in
# order not to be badly handled by the output module or misinterpreted
# by shell.
# GenericStripPunctChars  ""

# If the language you need to pass in $LANG is different
# from the standard ISO language code, you can specify
# which string to use instead. If you wish to use
# other than ISO charset for the specified language,
# you can add it's name (as accepted by iconv) as a
# third parameter in doublequotes.


GenericLanguage		  "en" "en" "utf-8"
GenericLanguage		  "de" "de" "utf-8"
GenericLanguage		  "es" "es" "utf-8"
GenericLanguage		  "fr" "fr" "utf-8"
GenericLanguage           "fr" "fr" "utf-8"

GenericLanguage		  "it" "it" "utf-8"

# AddVoice specifies which $VOICE string should be assigned to
# each language and symbolic voice name. All the voices you want
# to use must be specified here. This list will likely not be
# up-to-date, please check pico documentation and add the voices
# you want to use.

AddVoice        "en"    "FEMALE1"	"en-US"
AddVoice        "en"    "FEMALE2"	"en-GB"
AddVoice        "de"    "FEMALE1"	"de-DE"
AddVoice        "es"    "FEMALE1"	"es-ES"
AddVoice        "fr"    "FEMALE1"	"fr-FR"
AddVoice        "fr-fr"    "FEMALE1"       "fr-FR"
AddVoice        "fr-FR"    "FEMALE1"       "fr-FR"
AddVoice        "it"    "FEMALE1"	"it-IT"

# Yes, it's wrong, but this way you at least get something even when configured
# (by default) to use a male voice
AddVoice        "en"    "MALE1"		"en-US"
AddVoice        "en"    "MALE2"		"en-GB"
AddVoice        "de"    "MALE1"		"de-DE"
AddVoice        "es"    "MALE1"		"es-ES"
AddVoice        "fr"    "MALE1"		"fr-FR"
AddVoice        "fr-FR"    "MALE1"         "fr-FR"
AddVoice        "fr-fr"    "MALE1"         "fr-FR"
AddVoice        "it"    "MALE1"		"it-IT"

# Debug turns debugging on or off
# See speechd.conf for information where debugging information is stored
Debug 1

`

**Comment by sthibaul** [comment]
Ok, that's odd. Would you be able to test with the master branch, and putting `Debug 1` at the top of `pico-generic.conf`, so we get to see debugging pieces for the `AddVoice` stanzas?

**Comment by Shallowmallow** [comment]
I could try tomorrow  :)

**Comment by Shallowmallow** [comment]
Ok now it works in part with the last version .

But there is something weird

I use spd-say,  it works !
Then I use firefox, it works ! 
Then I use spd-say, nothing works anymore .



[speechd-new.log](https://github.com/brailcom/speechd/files/7171553/speechd-new.log)
[pico-generi-new.log](https://github.com/brailcom/speechd/files/7171554/pico-generi-new.log)

**Comment by sthibaul** [comment]
Great :) So fixed by 128a56cae89986fb7f554372b7d39f20f99f6c6a

**Comment by mothsART** [comment]
new release soon ?

**Comment by sthibaul** [comment]
Now done!
