### ISSUE TITLE
utf-8 encoding on generic module

### ISSUE THREAD

**Issue by mothsART** [brailcom/speechd#608]
I've tried to config a **speechd** using an new TTS by defaut : **gSpeech** (write in python langage).

1. New module config **/etc/speech-dispatcher/modules/gspeech-cli-generic.conf** :

```sh
GenericExecuteSynth "gspeech-cli -i \'$DATA\' -o /tmp/sound.wav && play /tmp/sound.wav"
GenericCmdDependency "gspeech-cli"
```

2. activate on **speechd.conf**:

```code
DefaultModule gspeech-cli-generic
```

3. If I pass utf-8 characters like this :

```sh
spd-say "J'aime le maïs, le cœur d’artichaut et les échalotes."
```

On gspeech, logs give me :

```code
J'aime le ma?s, le c?ur d?artichaut et les \udce9chalotes.
```

I can only reconized "\udce9" and decode with :

```python
text.encode('utf-8', 'surrogateescape').decode('latin-1')
```

If I launch :

```sh
gspeech-cli -i "J'aime le ma?s, le c?ur d?artichaut et les \udce9chalotes."
```

and logs looks like I wish :

```sh
J'aime le maïs, le cœur d’artichaut et les échalotes.
```

Locales give me :
```sh
locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by sthibaul** [comment]
How did you specify the character set in the `AddVoice` lines?

**Comment by sthibaul** [comment]
Sorry I meant: in the `GenericLanguage` lines

**Comment by mothsART** [comment]
```
GenericLanguage "fr" "french"
```

**Comment by sthibaul** [comment]
Then that is why: you need to specify the character set expected by the module, otherwise speech-dispatcher assumes latin1.

```
GenericLanguage "fr" "french"
```

**Comment by mothsART** [comment]
great, thanks

**Comment by axel-chamberland** [comment]
I apologize for necroposting, but I had a similar issue with generic module where my encoding for special characters (mainly French characters) was not working. 

I fixed it by adding:
`GenericDefaultCharset "utf-8"`

In the appropriate config of the generic module in modules/

**Comment by sthibaul** [comment]
one way or the other should be working, yes

but yes, you have to specify the encoding, otherwise the default is latin1
