### ISSUE TITLE
How could I use a custom speech engine?

### ISSUE THREAD

**Issue by Jcwscience** [brailcom/speechd#662]
I have Nvidia Flowtron running with a simple python script, and I would really like to use it as the default speech engine. Is there a way I can get data of the requested text and other things, and then pipe the audio back?

**Comment by sthibaul** [comment]
Sure, you just need to write a module, you can write it in python if you wish so. You just have to make it respect the ssip protocol, see ssip.html

**Comment by Jcwscience** [comment]
That page was exactly what I was needing, Perfect! Thanks for the quick response!

**Comment by heldiho53** [comment]
Sorry to hijack your post, @Jcwscience. @sthibaul How would I write an output module in python though? Client and output module aren't they same thing right? The output modules are all written in C, can libspeechd in Python actually be used to write an output module or just a client?

**Comment by sthibaul** [comment]
oh, right, sorry, ssip is not the protocol for modules. The https://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc/speech-dispatcher.html#Output-Modules part of the documentation is.

> The output modules are all written in C

The ones provided with speech-dispatcher are, yes, and helpers to write them are too. But modules are just executables, you could even write a module in bash.

> can speechd in Python actually be used to write an output module or just a client?

libspeechd is only the client part.

**Comment by sthibaul** [comment]
(btw, no worry about "hijacking", it was exactly on-topic so it was really exactly the place to ask the question)
