### ISSUE TITLE
Looking for symbol files in wrong location?

### ISSUE THREAD

**Issue by elboulangero** [brailcom/speechd#664]
Hi,

I was looking at a bug reported by a Kali Linux user at https://bugs.kali.org/view.php?id=7580. The issue itself was due to a missing package in Kali. However, something in the logs caught my eyes:

```
[Tue Feb 15 16:02:55 2022 : 315287] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/gender-neutral.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315303] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt/gender-neutral.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315308] speechd: Failed to load symbols 'gender-neutral.dic' for locale 'pt-br'
[Tue Feb 15 16:02:55 2022 : 315315] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/font-variants.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315323] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt/font-variants.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315328] speechd: Failed to load symbols 'font-variants.dic' for locale 'pt-br'
[Tue Feb 15 16:02:55 2022 : 315335] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/symbols.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315343] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt/symbols.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 315347] speechd: Failed to load symbols 'symbols.dic' for locale 'pt-br'
[Tue Feb 15 16:02:55 2022 : 315354] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/emojis.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 321349] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/base/emojis.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 348238] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/orca.dic': Arquivo ou diretório inexistente
[Tue Feb 15 16:02:55 2022 : 349044] speechd: Failed to open file '/usr/share/speech-dispatcher/locale/pt-br/orca-chars.dic': Arquivo ou diretório inexistente
```

I had a look in `/usr/share/speech-dispatcher/`:

```
$ ls /usr/share/speech-dispatcher | grep pt
pt
pt_BR
pt_PT
```

There's no `pt-br` directory in there... I started a Kali Linux system, I reconfigured the locale to `pt_BR`:

```
$ sudo dpkg-reconfigure locales
...
$ grep -v ^# /etc/locale.gen
pt_BR.UTF-8 UTF-8
```

Then restarted the system and looked again at the logs in `/run/user/1000/speech-dispatcher/log/speech-dispatcher.log`: indeed I can see the same error messages. `speechd` looks for files in the non-existent `pt-br` directory...

So why is speechd looking for a `pt-br` directory, while my locale is `pt_BR`, and all the directories in `/usr/share/speech-dispatcher/locale/` follow the naming convention `xx_XX` rather than `xx-xx`? Is it a known issue?

### Distribution

Kali Linux Rolling

### Version of Speech-dispatcher

```
$ dpkg -l | grep speech | awk '{print $2 " " $3}'
espeak-ng-data:amd64 1.50+dfsg-10
libespeak-ng1:amd64 1.50+dfsg-10
libflite1:amd64 2.2-2
libgsm1:amd64 1.0.18-2
libsonic0:amd64 0.2.0-11
libspeechd2:amd64 0.11.1-1
python3-speechd 0.11.1-1
speech-dispatcher 0.11.1-1
speech-dispatcher-audio-plugins:amd64 0.11.1-1
speech-dispatcher-espeak-ng 0.11.1-1
```

**Comment by jpwhiting** [comment]
Hey Arnaud it's been a while. Hope you are doing well. From checking the code it looks like speechd is looking for those files to generate a map of strings to replace based on the locale set. But it's likely from the DefaultLanguage setting in your ~/.config/speech-dispatcher/speechd.conf file. I bet you have pt-br in there instead of pt_BR. Either that or one of the applications using speech dispatcher is trying to use pt-br locale and is feeding that via libspeechd apis or something I bet.

**Comment by sthibaul** [comment]
> I bet you have pt-br in there instead of pt_BR

Probably not really the issue, as I'm having the same with fr-fr. Reading `ssip.texi`, it says

`@var{language-code} is the code of the language according to RFC 1766.`

So it's the protocol itself that says to use `pt-br` instead of `pt_BR`. speech-dispatcher would have to automatically turn `xx-yy` into `xx_YY` before loading symbols.

**Comment by elboulangero** [comment]
> Hey Arnaud it's been a while

Hi Jeremy! Nice to see you here, I hope you're doing great as well. Thanks for your quick feedback.

So let met clarify the test setup again, just to be crystal clear.

I started from scratch and created a new VM. I installed Kali Linux using the latest [weekly installer image](http://kali.download/base-images/kali-weekly/) (for information, the Kali installer is basically the Debian installer with minor changes). I choose to install with speech synthesis, and I selected the language "Portugual Brasil".

As a result, in the system installed, the UX is indeed in portuguese, and speech synthesis is enabled, and it speaks to me in Portuguese. I can check again what's the locale:

```
└─$ printenv | grep LANG
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
```

So far so good.

But when I check the logs in `/run/user/1000/speech-dispatcher/log/speech-dispatcher.log` I can still see the error messages.

> But it's likely from the DefaultLanguage setting in your ~/.config/speech-dispatcher/speechd.conf file. I bet you have pt-br in there instead of pt_BR

So I didn't explicitly set anything myself. If any configuration was done, it was done by the Debian installer, or maybe upon package installation by a postinst script of some package, or something like that.

Let me check in the system what has been configured:

```
└─# egrep -rn "pt(-br|_BR)" /etc/default
/etc/default/locale:2:LANG="pt_BR.UTF-8"
/etc/default/locale:3:LANGUAGE="pt_BR:pt:en"
/etc/default/espeakup:4:default_voice=pt-br

└─# egrep -rn "pt(-br|_BR)" /etc/speech-dispatcher 
/etc/speech-dispatcher/modules/espeak-mbrola-generic.conf:81:GenericLanguage              "pt-br" "pt-br" "utf-8"
/etc/speech-dispatcher/modules/espeak-mbrola-generic.conf:157:AddVoice        "pt-br" "MALE1"           "br1"
/etc/speech-dispatcher/modules/espeak-mbrola-generic.conf:158:AddVoice        "pt-br" "MALE2"           "br3"
/etc/speech-dispatcher/modules/espeak-mbrola-generic.conf:160:AddVoice        "pt-br" "FEMALE1"       "br4"
/etc/speech-dispatcher/modules/espeak-ng-mbrola-generic.conf:87:GenericLanguage           "pt-br" "pt-br" "utf-8"
/etc/speech-dispatcher/modules/espeak-ng-mbrola-generic.conf:208:AddVoice "pt-br" "MALE1" "br1"
/etc/speech-dispatcher/modules/espeak-ng-mbrola-generic.conf:209:AddVoice "pt-br" "MALE2" "br2"
/etc/speech-dispatcher/modules/espeak-ng-mbrola-generic.conf:210:AddVoice "pt-br" "MALE3" "br3"
/etc/speech-dispatcher/modules/espeak-ng-mbrola-generic.conf:211:AddVoice "pt-br" "FEMALE1" "br4"

└─$ ls /home/kali/.config/speech-dispatcher 
ls: não foi possível acessar '/home/kali/.config/speech-dispatcher': Arquivo ou diretório inexistente
```

So you're right @jpwhiting, there's some explicit configuration, the voice is set to `pt-br`.

> So it's the protocol itself that says to use pt-br instead of pt_BR. speech-dispatcher would have to automatically turn xx-yy into xx_YY before loading symbols.

@sthibaul So if I understand correctly, the value `default_voice=pt-br` in `/etc/default/espeakup` is correct, and the fault is in speech-dispatcher ?  I was curious to know what exactly sets the value in the file `/etc/default/espeakup`, but I couldn't find it.

**Comment by sthibaul** [comment]
> So if I understand correctly, the value default_voice=pt-br in /etc/default/espeakup is correct, and the fault is in speech-dispatcher ?

Yes. Just try with `spd-say`, you'll see that you get pt-br as well.

> I was curious to know what exactly sets the value in the file /etc/default/espeakup, but I couldn't find it

It's the espeakup finish-install script.
