### ISSUE TITLE
Module development documentation

### ISSUE THREAD

**Issue by loureirorg** [brailcom/speechd#737]
**Is your feature request related to a problem? Please describe.**
Not related to a software problem, just a lack of documentation.

I'm looking for documentation on how to develop a custom output module. 

Of course, the interface only, and not how to create a TTS engine.

I'm particularly interested in creating a module for Amazon Polly - i.e., just a wrapper, not an actual TTS engine. The idea is to send the text to Polly, retrieve the audio, and play.

**Describe the solution you'd like**
A tutorial on "How to create a 'hello world' module for speechd".

**Describe alternatives you've considered**
I Googled, I looked at the README - I couldn't find anything. My next step is to reverse-engineer an open-source module, like `speech-dispatcher-rhvoice`.

**Additional context**
Sorry if this information already exists, if it is on the README and I missed it. 

I spent about 1 hour looking for this information but couldn't easily find anything without getting deeper into concepts that I'm not sure will be useful for this purpose.

**Comment by sthibaul** [comment]
I guess you missed https://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc/speech-dispatcher.html#Output-Modules ?

**Comment by loureirorg** [comment]
Yes. That's exactly what I was looking for. Thanks!
