### ISSUE TITLE
command 'GET OUTPUT MODULE' returns string '(null)'  

### ISSUE THREAD

**Issue by clarkep** [brailcom/speechd#739]
### Steps to reproduce
The built-in test src/tests/clibrary2 tests the 'get output module' command using the C api. After building tests, run:
```
$ ./src/tests/clibrary2
```

### Obtained behavior
The relevant output is:

```
Trying to get the current output module...
Got module (null)`
```

The rest of the test runs fine. 

### Expected behavior

Expected 'Got module espeak-ng` as that is the first output module tested

### Behavior information
see below for log
### Distribution
OS: Gentoo/Linux x86_64 
Kernel: 5.15.26-gentoo-x86_64
Init system: systemd

### Version of Speech-dispatcher
0.11.1

**Comment by clarkep** [comment]
[debug.log](https://github.com/brailcom/speechd/files/8493864/debug.log)

**Comment by sthibaul** [comment]
Right, thanks!
