### ISSUE TITLE
Segmentation fault in speechd packaged version from Termux

### ISSUE THREAD

**Issue by sudomain** [brailcom/speechd#743]
### Steps to reproduce

Termux (a terminal emulator/nix environment for android) has a packaged version of speechd which results in a segmentation fault. I thought I'd bring it to your attention that the app exists and conceivably someone has had a working version of speechd on android. I opened an [issue with them which has details and logs](https://github.com/termux/termux-packages/issues/10380) in case the segfault isn't an actual issue with speechd but with [one of the Termux teams' patches](https://github.com/termux/termux-packages/tree/master/packages/speechd)

### Obtained behavior

Segmentation fault

### Expected behavior

No segfault

### Behavior information

Please follow the next step, to provide us with precious information about how things went wrong on your machine:

* Set `LogLevel` to 5 in your `/etc/speech-dispacher/speechd.conf`
* Restart your computer to make sure it gets taken into account
* Reproduce the issue
* Make a copy of the `speech-dispacher.log` file, it is usually found in `/run/user/1000/speech-dispatcher/log`. Also make a copy of `yourspeechmodule.log` (e.g. `espeak-ng.log`).
* Set `LogLevel` back to 3 in your `/etc/speech-dispacher/speechd.conf`
* Attach the `speech-dispatcher.log` and `yourspeechmodule.log` file to your bug report.

### Distribution
Termux? Technically not a distro

### Version of Speech-dispatcher
0.11.1

**Comment by sthibaul** [comment]
Apparently according to the termux bug entry, that was fixed by 3071e7d8553b245b4adc15edd44c5c309b881846
