### ISSUE TITLE
With flite, `spd-say -L` is empty although it works fine

### ISSUE THREAD

**Issue by genodeftest** [brailcom/speechd#746]
### Steps to reproduce

1. Have `flite` and `espeak-ng` installed with speech-dispatcher.
2. Configure speech-dispatcher to use `espeak-ng` in `/etc/speech-dispatcher/speechd.conf`:
```
AddModule "espeak-ng"                "sd_espeak-ng" "espeak-ng.conf"
DefaultModule espeak-ng
```
3. Try some test sentence, e.g.: `spd-say "some test sentence"`
4. List available languages: `spd-say -L`
5. Configure speech-dispatcher to use `flite` 
```
AddModule "flite"                    "sd_flite"     "flite.conf"
DefaultModule flite
```
6. Terminate all speech-dispatcher processes (or logout and login again)
7. Try some test sentence, e.g.: `spd-say "some test sentence"`
8. List available languages: `spd-say -L`

### Obtained behavior

At 3. and 7., the text is being synthesized to speech. At 4., I get a *very very* long list of languages. At 8., I get nothing:
```
$ spd-say -L
                     NAME                 LANGUAGE                  VARIANT
```
Which is unplausible because `spd-say` works. Also, flite is convinced that it has some voices installed:
```
$ flite -lv
Voices available: kal awb_time kal16 awb rms slt
```

### Expected behavior

As flite has at least one voice (the one that is chosen), and lists a few other voices, `spd-say -L` should list at least some voices/languages.

### Behavior information

Please follow the next step, to provide us with precious information about how things went wrong on your machine:

* Set `LogLevel` to 5 in your `/etc/speech-dispacher/speechd.conf`
* Restart your computer to make sure it gets taken into account
* Reproduce the issue
* Make a copy of the `speech-dispacher.log` file, it is usually found in `/run/user/1000/speech-dispatcher/log`. Also make a copy of `yourspeechmodule.log` (e.g. `espeak-ng.log`).
* Set `LogLevel` back to 3 in your `/etc/speech-dispacher/speechd.conf`
* Attach the `speech-dispatcher.log` and `yourspeechmodule.log` file to your bug report.

### Distribution

Fedora 35 (will try with Fedora 36 and speech-dispatcher 0.11.1 later)

### Version of Speech-dispatcher

speech-dispatcher-0.10.2-7.fc35.x86_64
speech-dispatcher-espeak-ng-0.10.2-7.fc35.x86_64
speech-dispatcher-flite-0.10.2-7.fc35.x86_64

### Other relevant software versions

espeak-ng-1.50-6.fc35.x86_64
flite-2.2-1.fc35.x86_64

**Comment by sthibaul** [comment]
Please update to version 0.11.1, see https://github.com/brailcom/speechd/issues/435
Thanks for the report anyway, that's really the kind of details which is very helpful to sort out issues :)

**Comment by genodeftest** [comment]
Oh, thanks for the quick response!
