### ISSUE TITLE
Segfault in `spd_close()`

### ISSUE THREAD

**Issue by Parakleta** [brailcom/speechd#762]
The changes made in dc945d84f9ddc43c1d247abd431f1b20d7fa9147 lead to a SegFault on FreeBSD due to an attempt to close a null `FILE *`.

I think the relevant code should look like:

```c
    if (connection->stream != NULL)
        fclose(connection->stream);
    connection->stream = NULL;
    close(connection->socket);
```

This mimics the closure behaviour on error in `get_reply()` in the same file.

**Comment by sthibaul** [comment]
Thanks for the report!
(I however don't think we shall `close` the underlying socket, `fclose` does that already)

**Comment by Parakleta** [comment]
Yes, you are correct. I hadn’t followed the `fdopen` behaviour correctly.
