### ISSUE TITLE
Add inflection parameter for espeak-ng config

### ISSUE THREAD

**Issue by sevapopov2** [brailcom/speechd#791]
At the moment there is no possibility to change eSpeak-ng's inflection as we can in NVDA or espeak-ng for iOS/Android.
It seems that now espeak-ng's inflection is always set to 50%, however I'd like to be able to set the exact same variant of inflection and pitch that I use in NVDA with voice Max. That's pitch 40, inflection 75.
Currently I am not able to change eSpeak's inflection, so I cannot change the variant to my liking.
Would it be possible to add a parameter in espeak-ng's config to change the inflection between 0 and 100 as it is done in NVDA?
Here's how it is done in [eSpeak's iOS App](https://github.com/espeak-ng/espeak-ng-ios-app/commit/d6cc1f3e9fa9057b7950607af62db20b6e85016e)
As far as I understood from issue discussion it's done with eSpeakRANGE parameter.
Thank you!

**Comment by sthibaul** [comment]
Is this not the  `pitch_range` parameter? See `spd-say`'s `-R` option. That is indeed setting the espeakRANGE parameter.

**Comment by sevapopov2** [comment]
I have just checked, yes -R parameter changes eSpeak's inflection, but I meant to add a config parameter to config file to be able to change it in Orca like we can do with maximum rate, or that is not how it works and I should write to Orca developers for them to include the inflection parameter to eSpeak's configuration?

**Comment by sthibaul** [comment]
> I meant to add a config parameter to config file to be able to change it in Orca like we can do with maximum rate

We have to add a parameter for the rate because the notion of lowest/highest value is not really well defined. In the case of the pitch range, it is just definitely between 0 and 100, with the default being 50, so I don't think it is useful to introduce min/max values in the config file, just like we don't have them for pitch, volume, etc.

> or that is not how it works and I should write to Orca developers for them to include the inflection parameter for eSpeak's configuration in voice settings

Orca's setting should be extended to include pitch range for configuration completeness, yes.
