### ISSUE TITLE
Sounding is higher on 50% pitch parameter compared to NVDA and other screen readers

### ISSUE THREAD

**Issue by sevapopov2** [brailcom/speechd#792]
### Steps to reproduce
1. Set pitch in Orca's preferences at 50% and listen how it sounds.
2. Make the same in NVDA and compaire the difference in sound. You can test it both in eSpeak-ng and in RHVoice. It's more noticeable with RHVoice that in Orca pitch is slightely higher than in NVDA.

### Obtained behavior
When setting pitch to 50% in Orca, it is higher on 5% than in NVDA.

### Expected behavior
If it is possible, it would be good to have the same pitch standardized percentage in all screen readers, to have the same sounding in 50% pitch in Orca as in NVDA.
As far as I understand it's controlled with speech-dispatcher, that's why I am reporting it here.

### Distribution
Arch Linux

### Version of Speech-dispatcher
0.11.3

**Comment by sthibaul** [comment]
speech-dispatcher is just passing over that value to espeak-ng.

It rather seems that it's orca which is introducing some tweaks:

```
src/orca/speechdispatcherfactory.py:
    def _set_pitch(self, acss_pitch):
        pitch = int(20 * max(0, min(9, acss_pitch)) - 90)
        self._send_command(self._client.set_pitch, pitch)
```

**Comment by sevapopov2** [comment]
Thank you, I checked and yes, the default pitch parameter in speech-dispatcher sounds exactly the same as in NVDA.
I created an issue in Orca's repository.
