### ISSUE TITLE
espeak-ng: strange sounds when reading some strings

### ISSUE THREAD

**Issue by alex19EP** [brailcom/speechd#793]
I am 90% sure that this is another bug in espeak's ssml but since I could not repeat it through espeak-ng cli but only through spd-say, I decided to write here first.

### Steps to reproduce

`spd-say -o espeak-ng -l 'ru' -y 'Russian+Max' -r 100 -w -x "<speak><mark name="0:4"/>read <mark name="5:10"/>bytes <mark name="11:15"/>from <mark name="16:21"/>their <mark name="22:27"/>input <mark name="28:31"/>and <mark name="32:37"/>write <mark name="38:41"/>the <mark name="42:47"/>bytes <mark name="48:50"/>to <mark name="51:56"/>their <mark name="57:64"/>output.<mark name="__spd_0"/> <mark name="65:68"/>The <mark name="69:73"/>real <mark name="74:79"/>magic <mark name="80:82"/>is <mark name="83:85"/>in <mark name="86:95"/> косая черта dev косая черта sr0.<mark name="__spd_1"/></speak>"`

### Obtained behavior

listen for a strange gurgling overtone on the second bytes word.

### Expected behavior

sound should be same as when executing:
`espeak-ng -v ru+max -s 449 -m '<speak><mark name="0:4"/>read <mark name="5:10"/>bytes <mark name="11:15"/>from <mark name="16:21"/>their <mark name="22:27"/>input <mark name="28:31"/>and <mark name="32:37"/>write <mark name="38:41"/>the <mark name="42:47"/>bytes <mark name="48:50"/>to <mark name="51:56"/>their <mark name="57:64"/>output.<mark name="__spd_0"/> <mark name="65:68"/>The <mark name="69:73"/>real <mark name="74:79"/>magic <mark name="80:82"/>is <mark name="83:85"/>in <mark name="86:95"/> косая черта dev косая черта sr0.<mark name="__spd_1"/></speak>'`

### Distribution

Arch Linux

### Version of Speech-dispatcher

0.11.3.r17.ga3acf81a
espeak-ng: 1.51.r587.g0f3fb42b

**Comment by sthibaul** [comment]
I'm not sure I'm actually able to reproduce the issue. I tried to use 0f3fb42b of espeak-ng, but I'm not sure to catch what gurgling overtone you mention. Can you reproduce it with a smaller rate so I can better grasp what's happening? Can you perhaps try to reduce the amount of text passed to spd-say? Perhaps you can record what you get with pulse's "monitor" device, to make sure whether I'm getting the same output as you get?

Also, in speech-dispatcher's espeak-ng.log you can see what is eventually actually passed to espeak-ng, to make sure what is supposed to be passed to it.

**Comment by sevapopov2** [comment]
It is possible to reproduce with issue starting from 60% rate in Orca and higher. On 60% rate these effects are not that possible but it is possible to hear them on higher rates, for example on 90 or 80%

**Comment by alex19EP** [comment]
> Can you reproduce it with a smaller rate so I can better grasp what's happening?

you can try 80 rate option for me it is more noticeable at 100 percent speed.

> Can you perhaps try to reduce the amount of text passed to spd-say?

string: `read bytes from their input and write the bytes`
which in ssml would be: `"<speak><mark name="0:4"/>read <mark name="5:10"/>bytes <mark name="11:15"/>from <mark name="16:21"/>their <mark name="22:27"/>input <mark name="28:31"/>and <mark name="32:37"/>write <mark name="38:41"/>the <mark name="42:47"/>bytes</speak>"`

can reproduce this issue. the strange sound would be at last word "bytes"

> Perhaps you can record what you get with pulse's "monitor" device, to make sure whether I'm getting the same output as you get?

I will try to do this if the simplified lines do not help you hear the problem.

> Also, in speech-dispatcher's espeak-ng.log you can see what is eventually actually passed to espeak-ng, to make sure what is supposed to be passed to it.

from there I took the ssml string.

just in case, I will clarify that it is important to check this in Russian. I didn't manage to repeat it with the English espeak's accent.

**Comment by alex19EP** [comment]
> just in case, I will clarify that it is important to check this in Russian. I didn't manage to repeat it with the English espeak's accent.

clarification. I couldn't reproduce it via cli, maybe I just don't know how to use spd-say, but when changing the language in orca to en-gb and en-us, this bug remains.

**Comment by sthibaul** [comment]
> I will try to do this if the simplified lines do not help you hear the problem.

This is what I'm getting with 

```
spd-say -o espeak-ng -l 'ru' -y 'Russian+Max' -r 100 -w -x "<speak><mark name="0:4"/>read <mark name="5:10"/>bytes <mark name="11:15"/>from <mark name="16:21"/>their <mark name="22:27"/>input <mark name="28:31"/>and <mark name="32:37"/>write <mark name="38:41"/>the <mark name="42:47"/>bytes</speak>"
```

: 
[test.wav.zip](https://github.com/brailcom/speechd/files/10051200/test.wav.zip)

I indeed don't really hear something strange.

**Comment by sevapopov2** [comment]
There is an additional sound effect on the last word byte. I don't know how to explain it, but there is a high pitched additional noize when espeak says the sound i. You can try to put the same phrase to espeak-ng command line and there will be no such effect.

**Comment by alex19EP** [comment]
> I indeed don't really hear something strange.

but there really is a sound that shouldn't be there.

here is 
[test.wav.zip](https://github.com/brailcom/speechd/files/10057165/test.wav.zip)
recorded with `espeak-ng` command there is no such artifact.

**Comment by sthibaul** [comment]
Ok, it's subtle, I'm not used to listening to such difference. Just to make sure: do you hear it in this:
[test.wav.zip](https://github.com/brailcom/speechd/files/10060389/test.wav.zip)

**Comment by alex19EP** [comment]
there is much distortion here but I can hear this artifact in file 1 and 2.

**Comment by sthibaul** [comment]
Ok, that's produced diretcly from espeak.

**Comment by sthibaul** [comment]
And to be sure, with this one?

[test.wav.zip](https://github.com/brailcom/speechd/files/10060653/test.wav.zip)

**Comment by alex19EP** [comment]
hmmm. it's strange. on my system espeak cli is not affected by this bug.

**Comment by sthibaul** [comment]
It's not the cli, it's an espeak program

**Comment by sthibaul** [comment]
Could you confirm on the third file ?

**Comment by alex19EP** [comment]
yep on the last one I can here it clearly

**Comment by alex19EP** [comment]
> It's not the cli, it's an espeak program

oh you mean the library.

**Comment by sthibaul** [comment]
Ok so it's really a by-default behavior of libespeak, nothing strange in how speechd tells espeak to speak

**Comment by sthibaul** [comment]
I'll report to espeak-ng

**Comment by alex19EP** [comment]
as I said, from the very beginning I thought that this was so, but I was confused by the fact that I could not reproduce this through the cli.

thank you for help as always!

**Comment by djphoenix** [comment]
@alex19EP @sthibaul

I have played with example some time, and the winner is... buffer size. I'm not sure how and why.

For sure, [CLI uses buffer size 0](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.c#L604), that means "default" and [raises to minimum, which is 60](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/speech.c#L281).

I see that there is a [configuration option for buffer size](https://github.com/brailcom/speechd/blob/master/config/modules/espeak-ng.conf#L44). Can you set it smaller and check that issue still reproducible?
