### ISSUE TITLE
Cannot set SpeechSynthesisVoice to female voice variant when espeak is the default speech synthesis module

### ISSUE THREAD

**Issue by guest271314** [brailcom/speechd#8]
Steps to reproduce the problem:
1. Execute window.speechSynthesis.getVoices()
2. Filter SpeechSynthesisVoice objects and select a SpeechSynthesisVoice object where "female" is included in SpeechSynthesisVoice "name" attribute

What is the expected behavior?
The selected SpeechSynthesisVoice object "name" attribute should correspond to the name of the voice variant expected by espeak

What went wrong?
The female voice variant is not selected, the male voice variant is output as audio

`espeak` expects voice variant name to be e.g., `"female1"` or `"english+f1"` not `"english+female1 espeak"` at Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=811160 or `"english+female1"` at Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1437422.

`````
<!DOCTYPE html>
<html>
 
<head>
<title>Cannot set SpeechSynthesisVoice to female voice variant when espeak is the default speech synthesis module</title>
<script>
window.speechSynthesis.cancel();
var text = "hello universe";
 
var handleVoices = () => {
window.speechSynthesis.onvoiceschanged = null;
voices = voices \|\| window.speechSynthesis.getVoices();
// filter female voice variants
voices = voices.filter(({
name: voiceName
}) => /^en-\|english/.test(voiceName) && /female/.test(voiceName));
// select "english" "female1" voice variant
var voice = voices.find(({name: voiceName}) => /^english\+female1/.test(voiceName));
console.log(voices, voice);
const utterance = new SpeechSynthesisUtterance();
utterance.text = text;
utterance.lang = "en-US";
utterance.voice = voice;
// `espeak` expects voice variant name to be e.g., `"female1"` or `"english+f1"`
// not `"english+female1 espeak"` at Chromium
// or `"english+female1"` at Firefox
console.log(utterance.voice.name);  //
window.speechSynthesis.speak(utterance);
 
}
window.speechSynthesis.onvoiceschanged = handleVoices;
var voices = window.speechSynthesis.getVoices();
if (voices.length) handleVoices();
 
</script>
</head>
<body>
</html>
`````

**Comment by sthibaul** [comment]
Err, well, yes, that is what espeak documents:

«
Alternatively there are some preset voice variants which can be applied to any of the language voices, by appending <code>+</code> and a variant name. Their effects are defined by files in <code>espeak-data/voices/!v</code>.
<p>
The variants are <code> +m1  +m2  +m3  +m4  +m5 +m6 +m7</code> for male voices, <code> +f1 +f2 +f3 +f4 +f5 </code> for female voices
»

So I don't see any bug on the espeak/speech-dispatcher side, and the bug is rather either in your javascript code, or in chromium/firefox. Where does this +female1 thing come from, actually? I'm not getting it when printing the voiceNames.

**Comment by guest271314** [comment]
Not sure where the "+female1" comes from. This is where Chromium apparently adds "espeak" to the voice name https://cs.chromium.org/chromium/src/chrome/browser/speech/tts_linux.cc?rcl=6810624d58594c3b2074f0bfe9a2651ed623883d&l=255

    
  ```
      native_data.name = native_voice->name;
        native_data.module = module;
        std::string key;
        key.append(native_data.name);
        key.append(" ");

```

at Firefox https://dxr.mozilla.org/mozilla-central/source/dom/media/webspeech/synth/speechd/SpeechDispatcherService.cpp#402

```
      if (strcmp(list[i]->variant, "none") != 0) {
        // In speech dispatcher, the variant will usually be the locale subtag
        // with another, non-standard suptag after it. We keep the first one
        // and convert it to uppercase.
        const char* v = list[i]->variant;
        const char* hyphen = strchr(v, '-');
        nsDependentCSubstring variant(v, hyphen ? hyphen - v : strlen(v));
        ToUpperCase(variant);

        // eSpeak uses UK which is not a valid region subtag in BCP47.
        if (variant.EqualsLiteral("UK")) {
          variant.AssignLiteral("GB");
        }

        lang.AppendLiteral("-");
        lang.Append(variant);
      }

      uri.Append(NS_ConvertUTF8toUTF16(lang));

      mVoices.Put(uri, new SpeechDispatcherVoice(
                    NS_ConvertUTF8toUTF16(list[i]->name),
                    NS_ConvertUTF8toUTF16(lang)));
    }
```

and possibly https://dxr.mozilla.org/mozilla-central/source/obj-x86_64-pc-linux-gnu/dom/bindings/SpeechSynthesisBinding.cpp?q=getVoices&redirect_type=direct#241.

Turned on voice variants at `~/.config/speech-dispatcher/espeak.conf` with `EspeakListVoiceVariants 1`. The only relevant file which could locate which explicitly has the text "FEMALE1" is `/etc/speech-dispatcher/espeak-generic.conf` at `AddVoice	"en"    "FEMALE1"   	"en-f"`, which am not certain what the expected effect is from reading the comment 

```
# AddVoice specifies which $VOICE string should be assigned to
# each language and symbolic voice name. All the voices you want
# to use must be specified here. This list will likely not be
# up-to-date, please check eSpeak documentation and add the voices
# you want to use. Or better use the native espeak module ('espeak'
# not 'espeak-generic')

```
?

Agreed, the issue is not espeak or speech-dispatcher side, though adjusting Chromium or Firefox code by way of filing issues is neither swift not guaranteed whatsoever. Unfortunately have not yet been able to access a 64-bit device to submit patches.

**Comment by guest271314** [comment]
Is https://github.com/brailcom/speechd/blob/master/src/clients/say/say.c#L145 involved in the procedure of setting the voice variant?

**Comment by sthibaul** [comment]
> Is https://github.com/brailcom/speechd/blob/master/src/clients/say/say.c#L145 involved in the procedure of setting the voice variant?

No, it's spd-say's source code, thus completely unrelated to the daemon and modules.

**Comment by sthibaul** [comment]
> AddVoice "en" "FEMALE1" "en-f", which am not certain what the expected effect is from reading the comment

Well, you can also read the speech-dispatcher documentation :)

“{symbolicname} is a symbolic name under which you wish this voice
to be available.”

These AddVoice lines provide e.g. the female1 alias for en-f. That's for espeak-generic anyway, which AIUI is not the module you are using (for good reason, since the espeak module is way better).

Really, please investigate where that +female1 comes from, I believe that's the problematic point.

**Comment by guest271314** [comment]
At Chromium "female" or "gender" are mentioned at 

- https://cs.chromium.org/chromium/src/extensions/common/manifest_constants.h?rcl=bed68dfde5b424976f34252ac142a9249291dea3&l=164

- https://cs.chromium.org/chromium/src/chrome/browser/speech/tts_mac.mm?q=female&dr=C&l=247

- https://cs.chromium.org/chromium/src/chrome/browser/speech/tts_controller.h?q=female&dr=CSs&l=46

- https://cs.chromium.org/chromium/src/chrome/common/extensions/api/tts.json?q=female&dr=C&l=18
