### ISSUE TITLE
Pulseaudio output does not work with easyeffects

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [brailcom/speechd#805]
### Steps to reproduce

Configure speech-dispatcher to use espeak-ng, to play to the default pulseaudio device. Run `spd-say 'hello'` while [`easyeffects`](https://github.com/wwmm/easyeffects) is running.

### Obtained behavior

Audio plays to the actual default pulseaudio device rather than being picked up by `easyeffects` and played to the "EasyEffects Sink" device.

### Expected behavior

Audio should play to "EasyEffects Sink" (note that this is what happens when I run `espeak-ng hello`).

### Behavior information

[speech-dispatcher.log](https://github.com/brailcom/speechd/files/10328472/speech-dispatcher.log)

espeak-ng.log is empty.

Note that whenever I run `spd-say`, I do see something being played to "EasyEffects Sink" for a split second and then it is moved to the default pulseaudio device. The easyeffects logs when I run `spd-say` versus `espeak-ng` are pretty much identical...

### Distribution

Debian

### Version of Speech-dispatcher

0.11.3

**Comment by sthibaul** [comment]
this seems to be hardwired in easyeffects, I don't know why: https://github.com/wwmm/easyeffects/blob/master/include/pipe_manager.hpp#L229

anyway it's not fixable in speechd itself, so transferring

**Comment by sthibaul** [comment]
Ah, no I can't transfer to a project which I don't manage, so closing it here, please open it on https://github.com/wwmm/easyeffects/issues

**Comment by ttttcrngyblflpp** [comment]
Just an FYI, it looks like judging by https://github.com/wwmm/easyeffects/issues/900#issuecomment-877713942 that people are alleging speech-dispatcher is problematic for one reason or another. I'm not sure if you care enough to have speech-dispatcher removed from the blocklist or not.

**Comment by sthibaul** [comment]
We do care about just fixing bugs, so no blocklist should be needed at all. That just needs fixing bugs instead of continuing to spread “pro tip: if you have troubles with sound, uninstall speech-dispatcher”.

I *guess* that the problem they are referring to might be the idleness issue https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2839 which is now solved.
