### ISSUE TITLE
contribution output modules?

### ISSUE THREAD

**Issue by sudomain** [brailcom/speechd#811]
Sorry if this isn't the correct place for this, but I'd prefer not to sign up for the mailing list for just this one thing. I've created a basic output module for speechd for a platform called Termux. Termux is a terminal emulator for Android which has a packaged version of speech-dispatcher. My output module uses one of Termux's tools called `termux-tts-speak` which speaks text given to it using a tts service installed on the device (usually Google, but others exist such as RHVoice).

It's very basic and uses the generic binary and config file. Does speechd want this as an output module? It's specific to Termux so I understand if the answer is no. I can see if they want it for their packaged version

**Comment by sthibaul** [comment]
I'm not sure to understand: termux actually ships speech-dispatcher?
Including the config file here is welcome, but if termux people  prefer to maintain it in their distribution of speech-dispatcher it may be better for them to keep them inside their workflow. It's rather like they prefer :)

**Comment by sudomain** [comment]
> I'm not sure to understand: termux actually ships speech-dispatcher?

Indeed and also espeak. I wanted a little better quality than espeak so I came up with this. In fact I made the file and tested it entirely on my phone.

I'll post it here tonight when it's a little more polished.
