### ISSUE TITLE
Recieve requested text over local port.

### ISSUE THREAD

**Issue by Jcwscience** [brailcom/speechd#812]
I need to know how to make a simple module that takes speech-dispatcher requests and outputs a string with just the text over a local port. I have a python based tts engine with a really good voice, and I have it set to receive strings over a local port and speak them.

**Describe the solution you'd like**
Could someone help me implement this code or something like it? Or is there a better way to receive speech events?
Any help is very much appreciated!

**Additional context**
I have a basic script here that should do what I want, however I don't know how to implement it exactly.
```
#include <speech-dispatcher/libspeechd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

void send_text(const char *text) {
    int sockfd;
    struct sockaddr_in dest_addr;

    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    memset(&dest_addr, 0, sizeof(dest_addr));
    dest_addr.sin_family = AF_INET;
    dest_addr.sin_addr.s_addr = inet_addr("127.0.0.1");
    dest_addr.sin_port = htons(12345);

    connect(sockfd, (struct sockaddr *)&dest_addr, sizeof(struct sockaddr));
    send(sockfd, text, strlen(text), 0);
    close(sockfd);
}

void myvoice_say_text(const char *text) {
    // Use your text-to-speech synthesis engine to generate speech output here
    // ...

    // Send the text string to a local port instead of generating speech output
    send_text(text);
}

SPDVoice myvoice = {
    .name = "myvoice",
    .language = "en-US",
    .rate = 1,
    .pitch = 0,
    .volume = 100,
    .stop = NULL,
    .pause = NULL,
    .resume = NULL,
    .is_speaking = NULL,
    .say_text = myvoice_say_text,
    .synthesis_module = NULL,
    .audio = NULL,
    .audio_connection_id = 0
};

void spd_voice_list_initialize_myvoice() {
    spd_voice_list_add(&myvoice);
}

```

**Comment by sthibaul** [comment]
Hello,

This is described in the documentation: https://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc/speech-dispatcher.html#How-to-Write-New-Output-Module

Samuel
