### ISSUE TITLE
The words "authentique", "authentiquement" and "authenticité" are not properly read in French

### ISSUE THREAD

**Issue by FiableDotBiz** [brailcom/speechd#828]
### Steps to reproduce

spd-say -l fr authentique
spd-say -l fr authenticité
spd-say -l fr authentiquement

### Obtained behavior

In the words "authentique", "authenticité" and "authentiquement", the "th" is read as an English "th" ([θ] in the International phonetic alphabet).

### Expected behavior

In the words "authentique", "authenticité" and "authentiquement", "th" should be read as a "t" ([t] in the International phonetic alphabet).

### Behavior information

Please follow the next step, to provide us with precious information about how things went wrong on your machine:

* Set `LogLevel` to 5 in your `/etc/speech-dispacher/speechd.conf`
* Restart your computer to make sure it gets taken into account
* Reproduce the issue
* Make a copy of the `speech-dispacher.log` file, it is usually found in `[speech-dispatcher.log](https://github.com/brailcom/speechd/files/11575229/speech-dispatcher.log). Also make a copy of `yourspeechmodule.log` (e.g. `espeak-ng.log`).
* Set `LogLevel` back to 3 in your `/etc/speech-dispacher/speechd.conf`
* Attach the `speech-dispatcher.log` and `yourspeechmodule.log` file to your bug report.
* Also attach your `speechd.conf` file and `yourspeechdmodule.conf` file.

### Distribution
updated Fedora workstation 38

### Version of Speech-dispatcher
0.11.4

[espeak-ng.log](https://github.com/brailcom/speechd/files/11575246/espeak-ng.log)
[espeak-ng-mbrola.log](https://github.com/brailcom/speechd/files/11575247/espeak-ng-mbrola.log)
[speech-dispatcher.log](https://github.com/brailcom/speechd/files/11575250/speech-dispatcher.log)

**Comment by sthibaul** [comment]
The exact pronunciation is not under the control of speech-dispatcher, you need to report it to the actual synthesis, here https://github.com/espeak-ng/espeak-ng/ . Notably we get the same with

```
espeak-ng -v fr authentique
espeak-ng -v fr authenticité
espeak-ng -v fr authentiquement
```
