### ISSUE TITLE
line buffering vs character buffering

### ISSUE THREAD

**Issue by novalis** [brailcom/speechd#833]
### Steps to reproduce

As I noted in #832, I have about 15,000 voices (I don't know why; I think I've just got default Debian).  So spd_list_synthesis_voices is slow, taking (after that PR) about 0.5s.  I can reduce that to 0.35s with:

```
diff --git a/src/api/c/libspeechd.c b/src/api/c/libspeechd.c
index 2ef3b9ea..c7b54feb 100644
--- a/src/api/c/libspeechd.c
+++ b/src/api/c/libspeechd.c
@@ -543,7 +543,7 @@ SPDConnection *spd_open2(const char *client_name, const char *connection_name,
        if (!connection->stream)
                SPD_FATAL("Can't create a stream for socket, fdopen() failed.");
        /* Switch to line buffering mode */
-       ret = setvbuf(connection->stream, NULL, _IONBF, SPD_REPLY_BUF_SIZE);
+       ret = setvbuf(connection->stream, NULL, _IOLBF, SPD_REPLY_BUF_SIZE);
        if (ret)
                SPD_FATAL("Can't set buffering, setvbuf failed.");
``` 

Note that this was the original code, before ec25ad9ada11327a6b890a4bf5b4036fa7e1d472 (in 2005).  Notice also the comment claiming this sets line buffering mode: while the code was changed, the comment was not.   

### Obtained behavior

`spd-say -L` reads one character at a time, leading to over 400k `read` syscalls.

### Expected behavior

Looks like 208 `read` syscalls afterwards (although some may be from other sources; at any rate, client i/o is no longer the bottleneck).

Note that https://github.com/brailcom/speechd/blob/95e7a9cb1f1e16a76857f525e31ec3b201e2ab2b/src/server/module.c#L502 has the same problem (including bogus comment), dating from  541f955205f0020375ec293e584268fdbbb5ee3f (committed a few minutes after ec25ad9ada11327a6b890a4bf5b4036fa7e1d472)

I didn't try changing that to see if it would further improve perf, since that seemed more complicated to test (since I am already running my distro's version of speech-dispatcher).  But I bet it would.

### Distribution

Debian

### Version of Speech-dispatcher

My comments are as-of 95e7a9cb1f1e16a76857f525e31ec3b201e2ab2b

**Comment by novalis** [comment]
@hhanke I know it's unlikely, but do you recall why you made this change back in 2005?

**Comment by sthibaul** [comment]
Note that this is related to #750  : we probably want to just use our own `getline` that is a cancellation point, buffers as desired, etc.

**Comment by sthibaul** [comment]
I'm thinking that we should just kill the two birds with one stone: add a `SPD_REPLY_BUF_SIZE`-sized buffer to `Connection`, rename our `getline` to `our_getline` and make it use that buffer to make full-size reads into it. Ideally it'd return a pointer into it, so that we don't have `getline` allocate a string only for `get_reply` to free it just after having copied it into `data.str`. `getline` would only have to `memmove` data in the rare case of having a non-`\n`-terminated piece at the end of the buffer. In such a case we can just `memmove` and restart over. If we still don't have a `\n` in the full buffer, it's a protocol error and we should just raise it so the connection gets closed.

Do you feel you could implement it?

**Comment by novalis** [comment]
It looks like the existing fallback `getline` function is nonstandard anyway (it ignores the initial value of `lineptr` and `n`).  So it will be good to get rid of it.

Is something like this what you are thinking?
https://github.com/brailcom/speechd/compare/master...novalis:buffering?expand=1

**Comment by sthibaul** [comment]
> Is something like this what you are thinking?

Yes, except that I don't think we want to reallocate the buffer, and leave it at SPD_REPLY_BUF_SIZE, servers are not supposed to return that-long lines.

Also, to avoid the `overwritten` complexity, we can make it take a `size_t *len`  that is filled with the size of the string, and the caller can then use `g_string_append_len` and avoid calling `strlen`. `read` then doesn't need a `-1`.

Also, rebase on master, I have already rewritten some pieces the same way you did :)

**Comment by novalis** [comment]
OK, I made a PR #837
