### ISSUE TITLE
Clarification needed about purpose and effects of the last commits

### ISSUE THREAD

**Issue by DidierSpaier** [brailcom/speechd#843]
I have downloaded the archive https://github.com/brailcom/speechd/releases/download/0.11.4/speech-dispatcher-0.11.4.tar.gz back in October 2022, which seems to have already applied all recent patches in its included files. As an example the file configure.ac includes already this line:

m4_define([MICRO_VERSION], [4])

as "changed" in commit  https://github.com/brailcom/speechd/commit/11f176801f38789fcf6bc50da196b5d7a9962702 from 3 weeks ago with the subject "0.11.4  release". What do i miss?

**Comment by sthibaul** [comment]
I was just porting the 0.11.4 release changes into master
