### ISSUE TITLE
Add API to list synthesis voices for a specified language or dialect

### ISSUE THREAD

**Issue by joanmarie** [brailcom/speechd#848]
I'm working on implementing fast, on-the-fly language switching in Orca. Thus I need to be able to *quickly* see if the current synthesizer supports a particular language + optional dialect. I'm using `list_synthesis_voices`, but it returns all of the voices. And for modules such as espeak (and variants thereof), the number returned is huge. It would be great to have API to just get the voices we're interested in.

**Comment by sthibaul** [comment]
I was planning to release an rc of 0.12 soon, could you check from master whether this commit fills your need, or do you prefer to wait for the rc?
