### ISSUE TITLE
Fails to build on macOS

### ISSUE THREAD

**Issue by mohd-akram** [brailcom/speechd#851]
### Steps to reproduce

Configure and make.

### Obtained behavior

```
libao.c:260:27: error: aliases are not supported on darwin
    __attribute__ ((weak, alias("libao_plugin_get")));
                          ^
1 error generated.
```

### Expected behavior

Builds successfully.

### Distribution

macOS 13.5

### Version of Speech-dispatcher

0.11.5

**Comment by sthibaul** [comment]
Ok, this that never actually worked since 2010 when plugins were introduced. Not sure how one is supposed to properly support plugins on macos.

**Comment by sthibaul** [comment]
Ah, well, I can as well just duplicate the definition, that's not much

**Comment by sthibaul** [comment]
Could you check that the build was indeed fixed?

**Comment by mohd-akram** [comment]
I get another unrelated error:

```
Undefined symbols for architecture x86_64:
  "_module_speak_sync", referenced from:
      _cmd_speak in module_process.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "_module_speak_sync", referenced from:
      _cmd_speak in module_process.o
ld: symbol(s) not found for architecture x86_64
make[3]: *** [sd_dummy] Error 1
make[3]: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "_module_speak", referenced from:
      _cmd_speak in module_process.o
     (maybe you meant: _module_speak_sync, _module_speak_ok , _module_speak_error )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [sd_generic] Error 1
make[3]: *** [sd_festival] Error 1
Undefined symbols for architecture x86_64:
  "_module_speak_sync", referenced from:
      _cmd_speak in module_process.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mohd-akram** [comment]
I worked around this issue by adding `-Wl,-U,_module_speak -Wl,-U,_module_speak_sync` to `LDFLAGS` in the configure stage and the build succeeds. However, there is another issue. There are explicit references to `.so` files in `src/modules/Makefile.am` which causes the binaries not to link properly. The dependencies should be handled via automake/libtool so no explicit reference to a `.so` file is made, which should fix the linking.

**Comment by sthibaul** [comment]
> I worked around this issue by adding -Wl,-U,_module_speak -Wl,-U,_module_speak_sync to LDFLAGS

What does this do?

**Comment by mohd-akram** [comment]
Linker flags to allow those two symbols to have no definition. Per the `ld(1)` man page:

```
-U symbol_name
             Specified that it is ok for symbol_name to have no definition.  With -two_levelnamespace, the resulting symbol will be marked dynamic_lookup which means dyld will search all loaded images.
```

**Comment by shindere** [comment]
Samuel Thibault (2023/08/11 08:22 -0700):
> Ok, this that never actually worked since 2010 when plugins were
> introduced. Not sure how one is supposed to properly support plugins
> on macos.

Hope to get a Mac soon and may be able to help on that.

Perhaps dylibs are the way?

**Comment by mohd-akram** [comment]
I resolved the linker issues by disabling the shims via `./configure --with-baratinoo=no --with-kali=no --with-voxin=no`. When I run `spd-say hello` or `spd-say -O` it stalls - nothing happens and I have to Ctrl-C to end it.

**Comment by sthibaul** [comment]
> Linker flags to allow those two symbols to have no definition. Per the `ld(1)` man page:
> 
> ```
> -U symbol_name
>              Specified that it is ok for symbol_name to have no definition.  With -two_levelnamespace, the resulting symbol will be marked dynamic_lookup which means dyld will search all loaded images.
> ```

Could you check that this
https://github.com/brailcom/speechd/pull/853
does it as expected on Darwin?

**Comment by sthibaul** [comment]
> Perhaps dylibs are the way?

AIUI, libtool etc. already produce dylibs, yes

**Comment by sthibaul** [comment]
> I resolved the linker issues by disabling the shims via `./configure --with-baratinoo=no --with-kali=no --with-voxin=no`. 

These shims are quite particular indeed, I have dropped them for now in #853.

**Comment by sthibaul** [comment]
> When I run `spd-say hello` or `spd-say -O` it stalls - nothing happens and I have to Ctrl-C to end it.

See the bug reporting template, for the information to provide in order to have any clue about what is going on.

Otherwise I can only answer "well, that sucks, but I don't have a Darwin system to try & debug".

**Comment by mohd-akram** [comment]
I tested your PR and it works. I investigated the issue with the hanging. It seems to be a problem with the generic module. Eg:

```
$ sd_generic dtk-generic.conf
INIT
299-Everything ok so far.
299 OK LOADED SUCCESSFULLY
701 BEGIN
Assertion failed: (message != NULL), function module_get_message_part, file module_utils.c, line 264.
Abort trap: 6
```

**Comment by mohd-akram** [comment]
I investigated this bug some more. The issue is with `sem_init`, it [does not work](https://stackoverflow.com/questions/1413785/sem-init-on-os-x) on macOS. It needs to be replaced with `sem_open`. Also, `sem_destroy` needs to be replaced with `sem_close` and `sem_unlink`.
