### ISSUE TITLE
Question about double left & right pointing angle brackets

### ISSUE THREAD

**Issue by Glog78** [brailcom/speechd#872]
I want to use Foliate with and piper-tts to let the epub text read out. Whenever there is a «» or to mark a speach in the epub its readed out as double right pointed angle bracket which i want to remove.

GenericStripPunctChars "«»" doesn't work.

Do you have any idea if i did a configuration mistake or if there is a bug?

Thank you alot in advance.

**Comment by sthibaul** [comment]
> GenericStripPunctChars "«»" doesn't work.

Please post the whole configuration file, so we can be sure exactly how you did it.

**Comment by Glog78** [comment]
here is my speechd.conf -> https://paste.rs/NzCjY
here is my piper-generic.conf ->  https://paste.rs/WLegX

Er öffnete den Mund, um es den anderen mitzuteilen – natürlich würde es wie jeder Reiter zuvor eine Frau sein –, als Masema plötzlich wie einen Fluch das Wort »Rabe!« knurrte
^^^ what i want to have read out without the double angle bracket

english translation : He opened his mouth to tell the others - of course, like every rider before him, it would be a woman - when Masema suddenly growled the word "Raven!" as if by curse.

**Comment by sthibaul** [comment]
erf, I missed the notification on this one, and now the paste is gone. Could you attached the files here rather than posting on paste.rs?

**Comment by 1256-bits** [comment]
I experience the same issue with rhvoice and espeak-ng
[RHVoice.conf.txt](https://github.com/brailcom/speechd/files/14865679/RHVoice.conf.txt)
[speechd.conf.txt](https://github.com/brailcom/speechd/files/14865681/speechd.conf.txt)
espeak-ng.conf is identical to the one in this repo

**Comment by sthibaul** [comment]
I realize only now: «» are not ascii, so the original code looking for stripping would be bogus.

I guess that nowadays one can assume that these files are encoded in utf-8?

**Comment by Glog78** [comment]
that's a good assumption from my point of few. I can't remember when i last used a pure ascii file.

**Comment by sthibaul** [comment]
I'm not thinking about pure ascii, but latin1/latin2/iso-8859-1/etc.

**Comment by Glog78** [comment]
my default currently is most likely utf-8 with modern terminals. Specially since the likes like vim / nvim and co using glyphs to look much better ;)
