### ISSUE TITLE
No audio on macOS using espeak-ng

### ISSUE THREAD

**Issue by mohd-akram** [brailcom/speechd#907]
### Steps to reproduce

Run:

```shell
spd-say -o espeak-ng hello
```

### Obtained behavior

No sound.

### Expected behavior

Sound is output.

### Behavior information

[speech-dispatcher.log](https://github.com/brailcom/speechd/files/15177424/speech-dispatcher.log)
[espeak-ng.log](https://github.com/brailcom/speechd/files/15177425/espeak-ng.log)

### Version of Speech-dispatcher
0.12.0-rc3

**Comment by sthibaul** [comment]
As the bug report template says, providing `speechd.conf` can be precious information.
From the speech-dispatcher.log, it seems that it is configured to use pulseaudio, is pulseaudio supported at all on macos?

**Comment by sthibaul** [comment]
(put another way: does `paplay` work on macos?)

**Comment by mohd-akram** [comment]
It is indeed due to it using Pulse. Setting `AudioOutputMethod` to `libao` resolves the issue. Thank you. I'll also build with `--with-pulse=no`.

**Comment by mohd-akram** [comment]
I'm facing a strange issue even with `libao`. If I run `speech-dispatcher` as a single application with the `-s` flag and then `spd-say`, it works. When using daemon mode, `speech-dispatcher` hangs and I'm unable to kill it and have to use `kill -9`. I've attached the new logs.

[speech-dispatcher.log](https://github.com/brailcom/speechd/files/15177852/speech-dispatcher.log)
[espeak-ng.log](https://github.com/brailcom/speechd/files/15177856/espeak-ng.log)

**Comment by sthibaul** [comment]
> speech-dispatcher hangs

How do you observe this? In the log you have provided, it duly sees the client going away, and after the usual 5s timeout, exits.

**Comment by mohd-akram** [comment]
The log says that but the process remains in `ps aux`. Notice also in the log it never reaches "Sent to audio" after sending samples. Attaching a debugger has shown that it gets stuck at https://github.com/brailcom/speechd/blob/b11eba42ab1c299937e7fb5f49b91b1eeb5b6f97/src/common/spd_audio.c#L267 with a `EXC_BAD_ACCESS` exception.

**Comment by sthibaul** [comment]
but you don't get this exception when the process is not daemonized? Does config.log say that the daemon function is detected? My guess would be that macos doesn't allow daemon processes to access audio

**Comment by mohd-akram** [comment]
> but you don't get this exception when the process is not daemonized?

Yes

> Does config.log say that the daemon function is detected?

Yup

> My guess would be that macos doesn't allow daemon processes to access audio

That could be it, although I would expect one to be able to handle the error. The crashing line in libao is [here](https://github.com/xiph/libao/blob/1.2.2/src/plugins/macosx/ao_macosx.c#L433). It seems the error handling in both speechd and libao is fine, so I'm not sure what's the issue. Perhaps it's a macOS bug.

**Comment by sthibaul** [comment]
The stack trace shows that it is inside `AudioComponentInstanceNew`, so not even a libao bug, but a bug in whatever provides that function. I don't think speechd can do much about it.

**Comment by mohd-akram** [comment]
Looked into this some more, and it seems macOS Frameworks have an issue if you call fork but not exec. There's some [documentation](https://developer.apple.com/library/archive/technotes/tn2083/_index.html#//apple_ref/doc/uid/DTS10003794-CH1-SUBSUBSECTION66) about this and example code on how to approach it. So I *think* this can be fixed in speechd.

**Comment by sthibaul** [comment]
```
        // Daemonize ourself.

        (void) daemon(0, 0);

        // exec ourself.

        (void) execve(execPath, args, environ);
```

Urgl...
