### ISSUE TITLE
Speech-dispatcher says u+201e and u+201d with english language text

### ISSUE THREAD

**Issue by hammera** [brailcom/speechd#909]
Hy,

I am not full sure this is a Speech-dispatcher issue, or simple missing few not imported Orca symbols the Speech-dispatcher hungarian dictionaries.
In Orca 46.0 version Speech-dispatcher the Espeak-ng module says the „ (u+201e character) with double low quote, and says the u+201d character with double right quote english language text.
Previous, this simbols are right localized In Orca source code the 44.2 version the Orca po/hu.po file, but Orca developers removed or changed I think this simbol handling after the 46.0 version (or before the 46.0 version publication), and this simbols translations perhaps missing.
How can I possible importing the previous right localized punctuation character names from the Orca 44 series po file?
I collected a Python scrypt the Orca 44 series chnames.py, punctuation_settings.py, chnames.py and mathsimbols.py translated symbol names with a four worksheet hungarian csv file.
The scrypt founded I think estimated 120 symbol translations the punctuation_settings.py file, and perhaps 60 or 70 character name translations, I am not remember right now the correct collected symbol translation numbers.

An interesting thing, with I don't understanding yet why happening:
Previous, for example in Orca 44.2 version says the u+0022 character with idézőjel hungarian translated text. This is the right translation in Orca the " symbol.

For example the u+0022 simbol I now hear with macskaköröm hungarian text the Orca 46 series version in Espeak-ng Speech-dispatcher module.
The orca/hu.po file this symbol translations are not changed the main branch into the Orca source repository. :-):-)

Perhaps this changed translations are comed out with other simbol files (nvda symbol.dic or emojy.dic the proper localization directory).
locale/hu directory existing the proper dictionary files into the Speech-dispatcher source directory of course.

So, my purpose:
1. I would like localizing the u+201e character and u+201d characters the proper Speech-dispatcher hungarian dictionary file, without a future automatic upgrade remove the new added two hungarian translation symbols.
2. In the case of the Hungarian language of the Speech-dispatcher, I would like to standardize the Hungarian language translations of Orca and other symbols for the texts that were used and defined in the old Orca version 44.2 the Speech-dispatcher hungarian symbols dictionary file the locale/hu directory, the Speech-dispatcher hungarian po file is 100% percent complete, remaining only the dictionary files related work.
It is possible that since some translations come from the NVDA screen reader translator template, some translations from the symbols.dic file, they overrode the translations after Orca version 46.0 for Speech-dispatcher that were previously used by Orca screen reader for version 44.2. :-):-)
If you can suggest a good way, I would start working on this unification related work under Debian 12 and would like testing the result, and when I'm ready, I'd open another pull request for this work related with mentions this issue ticket number.
Is it possible to prevent the .dic files containing translations from being automatically overwritten in the locale/hu subdirectory a future automatic symbol refreshing when anybody refreshing entire locale directory?
So, if anyway possible importing oldest character and punctuation character translations the Orca 44.2 version the locale/hu/orca-chars.dic and locale/hu/orca.dic, and unifying the other two dictionary files (emojis.dic, symbols.dic), I would like preventing automatic overwriting the future. :-):-)
If I might be wrong about the correct maintenance of symbol translations, please tell me the correct way so that I can unify the translations only in the Speech-dispatcher.

Kind regards, and excuse me the long issue report,

Attila

**Comment by hammera** [comment]
With u+201e and u+201d characters related:
The right symbol file with need editing the locale/hu/orca.dic, or locale/hu/orca-chars.dic?
Orca-chars.dic file contains now only the hu directory with 70 symbols, orca.dic contains only with three symbols.
My csv file are very similar with I collected, contains the character sequence or unicode character, the localized hungarian message, the punctuation level with defined the 44.2 series src/orca/punctuation_settings.py (I think this module or an another punctuation handling related module are removed with newer Orca source code versions, after the 45 series or perhaps after the 46 series version).

Attila

**Comment by sthibaul** [comment]
The underlying issue is essentially that in the NVDA repository, the hu translation is lagging behind a lot. Work should be happening there, and speech-dispatcher will just inherit it.

> In Orca 46.0 version Speech-dispatcher the Espeak-ng module says the „ (u+201e character) with double low quote, and says the u+201d character with double right quote english language text.

This should now be fixed with f0bd264a1bf6e31823048eda6d981965b1bd8290 . That was because the symbols were not defined in NVDA, and the way the orca symbols were imported were expecting these to be defined. I have changed the import to keep the orca symbols when the NVDA symbols are not available. I imported Orca 45.2, the last one with chnames.

> Previous, for example in Orca 44.2 version says the u+0022 character with idézőjel hungarian translated text. This is the right translation in Orca the " symbol.
> 
> For example the u+0022 simbol I now hear with macskaköröm hungarian text the Orca 46 series version in Espeak-ng Speech-dispatcher module.

That's to be fixed in NVDA, which is the one that defines U+0022 as "macskaköröm". We will then inherit it in speech-dispatcher.

>  Is it possible to prevent the .dic files containing translations from being automatically overwritten in the locale/hu subdirectory a future automatic symbol refreshing when anybody refreshing entire locale directory?

No. We do not want to take the time to maintain dictionaries, when the NVDA community is so much larger to maintain it.
