### ISSUE TITLE
Unlock the project on Weblate

### ISSUE THREAD

**Issue by rominf** [brailcom/speechd#951]
I translated speechd to Russian on Weblate. Later I noticed a few small mistakes with the translation and wanted to fix them, however the project became locked on Weblate (see the screenshot attached). I want this project to be unlocked, so that I fix the mistakes and my translation is accepted.

![Screenshot_20240816-100343.png](https://github.com/user-attachments/assets/8e5c5cd3-5058-4b09-a0bd-2dcce03c3c0e)

**Comment by sthibaul** [comment]
Weblate indeed notified me of the locking, it should be fixed now.

Thanks for your contribution!
