### ISSUE TITLE
Crash can occur depending on timing of the clearing of speaking_module

### ISSUE THREAD

**Issue by bbergquist0930** [brailcom/speechd#971]
https://github.com/brailcom/speechd/blame/615624a626d78503d09f7937dd56417c96587dfa/src/server/output.c#L969C14-L969C29

```
	if (!speaking_module)
		// We were cancelled
		return;
	pthread_mutex_lock(&playback_events_mutex);
	playback_events = g_slist_append(playback_events, entry);
	pthread_mutex_unlock(&playback_events_mutex);
	ret = write(speaking_module->pipe_speak[1], &c, 1);    // <----- speaking_module can be NULL here
	if (ret != 1)
		MSG(1, "Warning: couldn't write to pipe_speak: %d returned, (errno = %d, %s)\n", ret, errno, strerror(errno));
}
```

This has happened in practice and a core dump occurred and I was able to analyze this.  This `speaking_module` variable is global and is set and cleared by the `speak` thread but is also accessed in the `speak_queue_stop_or_pause`.  This global variable is not protected by any locking, so it is possible that the `speak` thread clears the variable and then the above code accesses the variable.  Even the test for NULL is not going to help because a thread swap could occur after that.

This really needs to have a lock.

**Comment by sthibaul** [comment]
Fixed by #972
