### ISSUE TITLE
Changing speech rate of a client affect pitch of another client

### ISSUE THREAD

**Issue by serezlan** [brailcom/speechd#979]
Execute following code:

client = speechd.SSIPClient('test')
client.set_output_module('voxin')
client.set_synthesis_voice('nathan-embedded-high')
client.set_rate(-80)
client.speak("Hello World!")
client.close()

I notice that pitch (and probably rate) of orca is affected. I expect the changes is isolated to above client only.

system:
- Debian 12
-   speech-dispatcher 0.11.4-2

**Comment by sthibaul** [comment]
I tried with various modules, including voxin, with speech dispatcher 0.11.4, 0.11.5, 0.12.0~rc4, without being able to reproduce this issue.

Which `sd_voxin` are you using? Is that the one shipped by speech-dispatcher, or a binary provided by voxin? I tried both the former and version 0.10.1 provided by voxin (I don't have a more recent version).

It is really more probably a parameter caching issue inside sd_voxin, so please test other modules to check whether it's related to voxin, and make sure which `sd_voxin` you are using. If it's the one shipped by voxin, I can't do much :) and this needs to be reported there.

**Comment by serezlan** [comment]
Got it.
I notice that I was using voxin RC release, so I retested again with version 3.4 non RC and it all works fine.

Thanks.
