### ISSUE TITLE
Default voice of module isn't based on locale

### ISSUE THREAD

**Issue by alexarnaud** [brailcom/speechd#99]
Environment:
- Debian 9.5 "Stretch"
- Speech Dispatcher RC1 or 0.8

Steps to reproduce:
1) Configure your computer to have an FR locale for example
2) Test this command:
spd-say -o espeak-ng "je suis connecté"

Result:
It is pronounced with it seems the default Espeak NG voice (maybe US voice)

Expected result:
It should be pronounced with the French voice

Another side effect is when you're using Mbrola and you've only installed the French voices it'll try to speak with US voices not installed, so it'll say silent that is annoying for a blind users relying only on speech synthesis.

Best regards,
Alex.

**Comment by alexarnaud** [comment]
@sthibaul This issue is partially fixed for me.

1) I use Speech Dispatcher 0.9 through Orca (Here on Debian 8 "Jessie)
2) I've only installed Mbrola fr voices
3) I'm using the default configuration of Speech Dispatcher (except for default module that is espeak instead of epseak-ng)
4) I set speech synthesis to Mbrola on Orca

Result:
No speec

Expected result:
Speech Dispatcher should speak with French voices

Best regards,
Alex.

**Comment by sthibaul** [comment]
Which mbrola fr voices  do you have?

In my tests, if I don't have mbrola-fr1 (which is the one selected by default by speech-dispatcher), I indeed do not get speech.

**Comment by sthibaul** [comment]
In the case of mbrola fr1 vs fr4, could you try to fix 
    /usr/lib/x86_64-linux-gnu/espeak-ng-data/voices/mb/mb-fr4 (and -en)
instead of 
    mbrola fr1 fr1_phtrans
you should have
    mbrola fr4 fr1_phtrans

**Comment by Inglebard** [comment]
Hi,
Sorry to "reopen" this.

If the default language is the current locale, what is the main goal of "DefaultLanguage" option ?

**Comment by sthibaul** [comment]
> what is the main goal of "DefaultLanguage" option ?

It is for the case when the client does not specify anything. We happened to make the spd-say client default to specifying the user's locale language, which in nowadays' habits seems to be what users expect: install speech-dispatcher, type `spd-say "something in my language"`, and hear that correctly.

We can probably add more comments about this in the configuration file.

**Comment by sthibaul** [comment]
Closed with #431
